<?php
declare(strict_types=1);
function render_admin(): void {
 $tabs=['dashboard'=>'داشبورد','products'=>'محصولات','categories'=>'دسته‌بندی‌ها','orders'=>'سفارش‌ها','customers'=>'کاربران و مشتریان','history'=>'سابقه ورود','company'=>'اطلاعات شرکت','shipping'=>'تنظیمات ارسال','security'=>'امنیت حساب'];$tab=is_string($_GET['tab']??null)?$_GET['tab']:'dashboard';if(!isset($tabs[$tab]))$tab='dashboard';
 page_header('مدیریت فروشگاه','',false,url('/admin'));?><div class="container page-content"><div class="page-heading"><h1>مدیریت نایلکس سادات</h1><a class="btn" href="/admin?tab=products&amp;edit=0">+ افزودن محصول با عکس</a><?php action_start('logout');?><button class="btn outline">خروج</button></form></div><div class="admin-layout"><aside class="panel admin-nav"><?php foreach($tabs as$k=>$label):?><a class="<?=$k===$tab?'active':''?>" href="/admin?tab=<?=h($k)?>"><?=h($label)?></a><?php endforeach;?></aside><section class="admin-content"><?php
 switch($tab){case 'dashboard':
 $count=query('SELECT COUNT(*) FROM ns_orders')->fetchColumn();$revenue=query("SELECT COALESCE(SUM(total),0) FROM ns_orders WHERE status IN ('PAID','SHIPPED','DELIVERED')")->fetchColumn();$products=query('SELECT COUNT(*) FROM ns_products WHERE active=1')->fetchColumn();?><div class="stat-grid"><?php foreach(['تعداد سفارش‌ها'=>$count,'دریافتی سفارش‌های پرداخت‌شده'=>$revenue,'محصولات فعال'=>$products]as$label=>$value):?><div class="panel"><p><?=h($label)?></p><strong><?=money($value)?></strong></div><?php endforeach;?></div><div class="panel"><h2>محصولات پرفروش</h2><?php $best=all("SELECT i.name,SUM(i.quantity) quantity FROM ns_order_items i JOIN ns_orders o ON o.id=i.order_id WHERE o.status IN ('PAID','SHIPPED','DELIVERED') GROUP BY i.product_id,i.name ORDER BY quantity DESC LIMIT 5");foreach($best as$b)echo '<p class="split-row"><span>'.h($b['name']).'</span><b>'.money($b['quantity']).' واحد</b></p>';if(!$best)echo '<p>پس از اولین پرداخت، آمار اینجا نمایش داده می‌شود.</p>';?></div><?php break;
 case 'products': admin_products();break;
 case 'categories':?><div class="panel"><h2>دسته‌بندی‌ها</h2><?php action_start('category','inline-form','/admin');hidden('id',0);?><input name="name" required minlength="2" maxlength="120" placeholder="نام دسته‌بندی جدید"><button class="btn">افزودن</button></form><?php foreach(all('SELECT * FROM ns_categories ORDER BY id')as$c):?><div class="inline-form"><?php action_start('category','inline-form','/admin');hidden('id',$c['id']);?><input name="name" required value="<?=h($c['name'])?>"><button class="btn outline">ذخیره</button></form><?php action_start('delete_category','','/admin');hidden('id',$c['id']);?><button class="icon-button" data-confirm="دسته‌بندی بدون محصول حذف شود؟">حذف</button></form></div><?php endforeach;?></div><?php break;
 case 'customers':?><div class="panel"><h2>کاربران و مشتریان</h2><?php foreach(all("SELECT id,name,username,wholesale_status,created_at FROM ns_users WHERE role='CUSTOMER' ORDER BY id DESC LIMIT 500")as$u):?><div class="customer-row"><div><strong><?=h($u['name'])?></strong><p><?=h($u['username'])?></p><span class="status"><?=h(['NONE'=>'عادی','PENDING'=>'در انتظار بررسی','APPROVED'=>'تأیید شده','REJECTED'=>'رد شده'][$u['wholesale_status']])?></span></div><?php action_start('customer','buy-row','/admin');hidden('id',$u['id']);?><button name="status" value="APPROVED" class="btn">تأیید عمده</button><button name="status" value="REJECTED" class="btn outline">رد درخواست</button></form></div><?php endforeach;?></div><?php break;
 case 'history':?><div class="panel"><h2>سابقه ورود کاربران</h2><p>۱۰۰ رویداد اخیر؛ زمان به وقت تهران است. تاریخچه هنگام ورود تا ۹۰ روز نگهداری می‌شود.</p><div class="table-scroll"><table><thead><tr><th>نام</th><th>نام کاربری / موبایل</th><th>رویداد</th><th>زمان</th><th>مرورگر اعلام‌شده</th></tr></thead><tbody><?php foreach(all('SELECT l.*,u.name,u.username FROM ns_login_events l JOIN ns_users u ON u.id=l.user_id ORDER BY l.id DESC LIMIT 100')as$e):?><tr><td><?=h($e['name'])?></td><td><?=h($e['username'])?></td><td><?=h(['LOGIN'=>'ورود','REGISTER'=>'ثبت‌نام','PASSWORD_CHANGE'=>'تغییر رمز'][$e['kind']]??$e['kind'])?></td><td><?=h((new DateTimeImmutable($e['created_at'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Asia/Tehran'))->format('Y/m/d H:i'))?></td><td class="agent-cell"><?=h($e['user_agent'])?></td></tr><?php endforeach;?></tbody></table></div></div><?php break;
 case 'company':$s=settings();action_start('company','panel form-stack','/admin');?><h2>اطلاعات شرکت</h2><p>این اطلاعات در تماس با ما، درباره ما و پایین سایت نمایش داده می‌شوند.</p><?php field('نام رسمی شرکت','company_name',$s['company_name']);field('تلفن عمومی','company_phone',$s['company_phone'],'text',false);field('ایمیل عمومی','company_email',$s['company_email'],'email',false);field('کد پستی','company_postal_code',$s['company_postal_code'],'text',false);field('ساعات پاسخ‌گویی','company_hours',$s['company_hours'],'text',false);textarea_field('نشانی شرکت','company_address',$s['company_address']);textarea_field('درباره شرکت','company_about',$s['company_about']);?><button class="btn">ذخیره اطلاعات شرکت</button></form><?php break;
 case 'shipping':$s=settings();action_start('shipping','panel form-stack','/admin');?><h2>تنظیمات ارسال</h2><?php field('هزینه ارسال ثابت (تومان)','shipping',$s['shipping'],'number');field('ارسال رایگان بالای مبلغ (تومان)','free_above',$s['free_above'],'number');?><p>هزینه صفر: همیشه رایگان؛ آستانه صفر: غیرفعال کردن شرط ارسال رایگان.</p><button class="btn">ذخیره تنظیمات</button></form><?php break;
 case 'security':password_form();break;
 case 'orders':?><div class="panel"><h2>مدیریت سفارش‌ها</h2><?php $orders=all('SELECT * FROM ns_orders ORDER BY id DESC LIMIT 200');if(!$orders)echo '<p>هنوز سفارشی ثبت نشده است.</p>';foreach($orders as$o):?><details class="admin-order"><summary><span><?=h($o['code'])?> · <?=h($o['name'])?></span><span class="status"><?=h(order_status($o['status']))?></span><b><?=money($o['total'])?> تومان</b></summary><p><?=h($o['phone'])?> · <?=h($o['address'])?></p><?php foreach(all('SELECT name,quantity,price FROM ns_order_items WHERE order_id=?',[$o['id']])as$i):?><p><?=h($i['name'])?> × <?=money($i['quantity'])?></p><?php endforeach;if($o['reference']):?><p>شناسه پرداخت <?=h($o['reference'])?></p><?php endif;action_start('order','buy-row','/admin');hidden('id',$o['id']);if($o['status']==='PAID'):?><button class="btn" name="status" value="SHIPPED">ثبت ارسال</button><?php elseif($o['status']==='SHIPPED'):?><button class="btn" name="status" value="DELIVERED">ثبت تحویل</button><?php elseif($o['status']==='PENDING'&&!$o['authority']):?><button class="btn outline" name="status" value="CANCELLED">لغو و آزادسازی موجودی</button><?php endif;?></form><?php if(in_array($o['status'],['PENDING','EXPIRED','PAYMENT_REVIEW'],true)&&$o['authority']):action_start('verify_order','','/admin');hidden('id',$o['id']);?><p>برای بررسی پرداخت یا تلاش مجدد جهت تأمین موجودی پرداخت دیرهنگام، از این دکمه استفاده کنید.</p><button class="btn outline">بررسی مجدد پرداخت در زرین‌پال</button></form><?php endif;?></details><?php endforeach;?></div><?php break;
 }?></section></div></div><?php page_footer();
}
function admin_products(): void {
 $edit=isset($_GET['edit'])?number_input('edit',0,PHP_INT_MAX,$_GET):null;$p=$edit?one('SELECT * FROM ns_products WHERE id=?',[$edit]):null;
 if($edit&&!$p)throw new ShopError('محصول پیدا نشد.',404);
 ?><div class="panel"><div class="section-heading"><h2>محصولات</h2><a class="btn" href="/admin?tab=products&edit=0">+ محصول جدید</a></div>
 <?php if($edit!==null):$p=$p?:['id'=>0,'version'=>1,'name'=>'','slug'=>'','description'=>'','retail'=>'','wholesale'=>'','minimum'=>10,'stock'=>0,'unit'=>'بسته','image'=>'','category_id'=>0,'featured'=>0];?><form method="post" action="/admin" enctype="multipart/form-data" class="product-form form-stack" data-product-form><?php csrf_field();hidden('action','product');hidden('id',$p['id']);hidden('version',$p['version']);?><h3><?=$p['id']?'ویرایش محصول':'افزودن محصول'?></h3><div class="form-grid"><?php foreach(['name'=>'نام محصول','slug'=>'شناسه انگلیسی آدرس','retail'=>'قیمت خرده (تومان)','wholesale'=>'قیمت عمده (تومان)','minimum'=>'حداقل تعداد عمده','stock'=>'موجودی','unit'=>'واحد فروش']as$key=>$label)field($label,$key,$p[$key],in_array($key,['retail','wholesale','minimum','stock'])?'number':'text');?><label>دسته‌بندی<select name="category_id" required><?php foreach(all('SELECT * FROM ns_categories')as$c):?><option value="<?=$c['id']?>" <?=$p['category_id']==$c['id']?'selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select></label><label class="check-label"><input type="checkbox" name="featured" <?=$p['featured']?'checked':''?>>محصول ویژه صفحه اصلی</label></div><?php textarea_field('توضیحات محصول','description',$p['description'],true);?><label>آپلود عکس محصول<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" data-photo></label><small>عکس JPEG، PNG یا WebP تا ۵ مگابایت و ۱۲ مگاپیکسل. عکس هنگام ذخیره محصول بهینه و ذخیره می‌شود.</small><img data-preview src="<?=h($p['image']?:'/products/hero.svg')?>" width="160" height="160" alt="پیش‌نمایش تصویر" class="upload-preview"><?php field('مسیر تصویر فعلی (پس از انتخاب فایل لازم نیست تغییر دهید)','image',$p['image'],'text',false);?><div class="buy-row"><button class="btn">ذخیره محصول</button><a class="btn outline" href="/admin?tab=products">انصراف</a></div></form><?php endif;?><div class="table-scroll"><table><thead><tr><th>محصول</th><th>قیمت خرده / عمده</th><th>موجودی</th><th>عملیات</th></tr></thead><tbody><?php foreach(all('SELECT * FROM ns_products WHERE active=1 ORDER BY id DESC LIMIT 500')as$p):?><tr><td><?=h($p['name'])?></td><td><?=money($p['retail'])?> / <?=money($p['wholesale'])?></td><td><?=money($p['stock'])?></td><td><a class="text-link" href="/admin?tab=products&edit=<?=$p['id']?>">ویرایش</a><?php action_start('delete_product','','/admin');hidden('id',$p['id']);?><button class="icon-button" data-confirm="محصول از فروشگاه حذف شود؟ سوابق سفارش باقی می‌مانند.">حذف</button></form></td></tr><?php endforeach;?></tbody></table></div></div><?php
}
