<?php
declare(strict_types=1);
function render_route(string $path): void {
 if($path!=='/'&&str_ends_with($path,'/')){
  $clean=rtrim($path,'/');
  if(preg_match('#^/(?:products(?:/[a-z0-9-]+)?|categories/[0-9]+-[a-z0-9-]+|about|contact|faq|wholesale)$#',$clean)){
   $query=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_QUERY);
   redirect(url($clean).($query!==null&&$query!==false?'?'.$query:''),301);
  }
  $path=$clean;
 }
 if(str_starts_with($path,'/categories/')&&category_page($path))return;
 if($path==='/robots.txt'){header('Content-Type: text/plain; charset=utf-8');echo "User-agent: *\nAllow: /\nDisallow: /install\nSitemap: ".url('/sitemap.xml');return;}
 if($path==='/sitemap.xml'){require_once __DIR__.'/sitemap.php';serve_sitemap();return;}
 if($path==='/admin'){if((current_user()['role']??'')!=='ADMIN')redirect('/login');require __DIR__.'/admin.php';render_admin();return;}
 if($path==='/'){home_page();return;}
 if($path==='/products'){catalog_page();return;}
 if(preg_match('#^/products/([a-z0-9-]+)$#',$path,$m)){detail_page($m[1]);return;}
 if(in_array($path,['/cart','/checkout'],true)){cart_page($path==='/checkout');return;}
 if(in_array($path,['/login','/register','/wholesale'],true)){auth_page($path!=='/login',$path==='/wholesale');return;}
 if($path==='/forgot-password'){page_header('بازیابی رمز عبور','',false);echo '<div class="container page-content"><div class="panel auth-form"><h1>بازیابی رمز با پیامک</h1><p>ارسال پیامک هنوز توسط مدیر فروشگاه پیکربندی نشده است. برای بازیابی حساب با پشتیبانی تماس بگیرید.</p><a class="btn" href="/contact">تماس با پشتیبانی</a><a class="text-link" href="/login">بازگشت به ورود</a></div></div>';page_footer();return;}
 if($path==='/account'){account_page();return;}
 if($path==='/track'){track_page();return;}
 if(in_array($path,['/about','/contact','/faq'],true)){info_page($path);return;}
 http_response_code(404);page_header('صفحه پیدا نشد','',false);echo '<div class="empty-state"><h1>صفحه پیدا نشد</h1><a class="btn" href="/">بازگشت به فروشگاه</a></div>';page_footer();
}
function home_page(): void {
 page_header('تولید و فروش عمده نایلون، کیسه زباله و یکبار مصرف','خرید عمده و خرده نایلون، نایلکس، کیسه زباله، سفره رولی و کیسه فریزر از تولیدکننده نایلکس سادات؛ قیمت کارخانه و امکان سفارش برای فروشگاه‌ها و رستوران‌ها.',true,url('/'));
 json_ld(['@context'=>'https://schema.org','@type'=>'WebSite','name'=>'نایلکس سادات','alternateName'=>'سادات پخش','url'=>url('/')]);?>
 <section class="container hero"><div class="hero-copy"><div class="eyebrow">انتخاب مطمئن خانه و کسب‌وکار شما</div><h1>نایلکس سادات | تولید و پخش عمده نایلون، کیسه زباله و لوازم یکبار مصرف</h1><p class="hero-tagline">کیفیت در هر لایه، آسودگی در هر خرید.</p><p>از نیازهای روزمره خانه تا سفارش‌های عمده فروشگاه شما؛<br>تولید و فروش عمده نایلون، نایلکس یکبار مصرف، کیسه زباله و محصولات بسته‌بندی با قیمت کارخانه. برای خرید خرده یا تأمین فروشگاه و رستوران، محصولات و شرایط همکاری را بررسی کنید.</p><div class="hero-buttons"><a href="/products" class="btn">مشاهده محصولات <?=icon('arrow')?></a><a href="/wholesale" class="hero-secondary">خرید عمده و همکاری ←</a></div><div class="hero-proof"><span class="proof-icon"><?=icon('leaf')?></span><div><b>همراه جزئیات کوچک زندگی</b><small>مواد اولیه مرغوب، انتخابی ماندگار</small></div><div class="proof-divider"></div><span class="made-in">ساخت ایران <span>با افتخار و اطمینان</span></span></div></div><div class="hero-art"><span class="orbit orbit-one"></span><span class="orbit orbit-two"></span><div class="floating-note"><span><?=icon('leaf')?></span><div><b>کیفیت از مواد اولیه شروع می‌شود</b><small>مقاوم، کاربردی و قابل اعتماد</small></div></div><img class="hero-product" src="/products/hero.svg" alt="محصولات بسته‌بندی نایلکس سادات" width="670" height="530" fetchpriority="high"><div class="hero-caption">✓ برای خانه، برای کسب‌وکار، برای شما</div></div></section>
 <div class="container benefits"><?php foreach(['truck'=>'ارسال به سراسر ایران','shield'=>'کیفیت قابل اعتماد','discount'=>'قیمت ویژه خرید عمده','support'=>'همراهی در خرید']as$symbol=>$b):?><div><span><?=icon($symbol)?></span><div><strong><?=h($b)?></strong><p>همراه خانه و کسب‌وکار شما</p></div></div><?php endforeach;?></div>
 <section class="container category-section"><div class="section-heading"><div><span class="eyebrow">هر نیاز، یک انتخاب مناسب</span><h2>دسته‌بندی محصولات</h2></div><a href="/products">همه دسته‌بندی‌ها ←</a></div><div class="category-grid"><?php foreach(seo_categories()as$i=>$c):?><a href="<?=h(category_path($c))?>" class="category-tile tile-<?=$i?>"><span class="category-illustration"><?=icon(category_icon($c['name']))?></span><h3><?=h($c['name'])?></h3><span>مشاهده محصولات ←</span></a><?php endforeach;?></div></section>
 <section class="featured-section"><div class="container"><div class="section-heading"><div><span class="eyebrow">انتخاب‌های کاربردی، کیفیت همیشگی</span><h2>پیشنهادهای نایلکس سادات</h2></div><a href="/products">مشاهده همه محصولات ←</a></div><div class="product-grid"><?php foreach(all('SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND p.featured=1 ORDER BY p.id LIMIT 8')as$p)product_card($p);?></div></div></section>
 <section class="container wholesale-banner"><div class="banner-art"><?=icon('box')?></div><div><span class="eyebrow">شریک تأمین کسب‌وکار شما</span><h2>فروش عمده و همکاری با فروشگاه‌ها</h2><p>برای خرید عمده نایلون زباله با قیمت کارخانه یا سفارش عمده سفره رولی یکبار مصرف برای رستوران، مدل محصول و تعداد موردنیاز را انتخاب کنید. قیمت عمده و حداقل سفارش هر کالا مشخص است.</p><div class="banner-checks"><span>✓ قیمت ویژه همکاران</span><span>✓ خرید مستقیم و آسان</span></div></div><a class="btn" href="/wholesale">درخواست همکاری ←</a></section><section class="container about-strip"><span class="about-leaf"><?=icon('leaf')?></span><div><h2>چرا نایلکس سادات؟</h2><p>تأمین مستقیم از تولیدکننده، قیمت خرده و عمده مشخص و امکان پیگیری سفارش؛ برای انتخاب اندازه و مدل مناسب با ما در ارتباط باشید.</p></div><a href="/about">بیشتر با ما آشنا شوید ←</a></section><?php page_footer();
}
function catalog_page(): void {
 $q=text_input('q',0,120,$_GET);$category=isset($_GET['category'])?number_input('category',0,PHP_INT_MAX,$_GET):0;$max=isset($_GET['max'])?number_input('max',0,100000000,$_GET):100000000;$sort=$_GET['sort']??'';
 if($category&&!$q&&!isset($_GET['max'])&&!isset($_GET['sort'])){$c=one('SELECT * FROM ns_categories WHERE id=?',[$category]);if($c)redirect(category_path($c),301);}
 $order=match($sort){'low'=>'p.retail ASC','high'=>'p.retail DESC',default=>'p.id DESC'};$sql='SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND p.retail<=?';$args=[$max];if($category){$sql.=' AND p.category_id=?';$args[]=$category;}if($q!==''){$sql.=' AND p.name LIKE ?';$args[]='%'.$q.'%';}$products=all($sql.' ORDER BY '.$order.' LIMIT 100',$args);
 page_header('فروشگاه محصولات','مقایسه و خرید انواع نایلون، نایلکس و محصولات بسته‌بندی با قیمت عمده و خرده.',!$q&&!$category&&!isset($_GET['max'])&&!isset($_GET['sort']),url('/products'));?><div class="container page-content"><div class="page-heading"><h1>فروشگاه محصولات</h1><span><?=money(count($products))?> محصول</span></div><div class="catalog-layout"><form action="/products" class="filter-panel"><h3>فیلتر محصولات</h3><?php field('جستجو','q',$q,'text',false);?><label>دسته‌بندی<select name="category"><option value="0">همه دسته‌بندی‌ها</option><?php foreach(all('SELECT * FROM ns_categories')as$c):?><option value="<?=$c['id']?>" <?=$category==(int)$c['id']?'selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select></label><?php field('حداکثر قیمت (تومان)','max',$max,'number');?><label>مرتب‌سازی<select name="sort"><option value="">پیشنهاد فروشگاه</option><option value="low" <?=$sort==='low'?'selected':''?>>ارزان‌ترین</option><option value="high" <?=$sort==='high'?'selected':''?>>گران‌ترین</option></select></label><button class="btn">اعمال فیلتر</button><a href="/products" class="text-link">حذف فیلترها</a></form><div class="product-grid catalog-grid"><?php foreach($products as$p)product_card($p);if(!$products)echo '<div class="empty-state">محصولی پیدا نشد؛ فیلترها را تغییر دهید.</div>';?></div></div></div><?php page_footer();
}
function detail_page(string $slug): void {
 $p=one('SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.slug=? AND p.active=1',[$slug]);if(!$p){http_response_code(404);page_header('محصول پیدا نشد','',false);echo '<div class="empty-state"><h1>محصول پیدا نشد</h1></div>';page_footer();return;}
 $u=current_user();$approved=($u['wholesale_status']??'')==='APPROVED';page_header('خرید '.$p['name'],mb_substr($p['description'],0,155),true,url('/products/'.$slug),url($p['image']),'product');
 json_ld(['@context'=>'https://schema.org','@type'=>'Product','name'=>$p['name'],'description'=>$p['description'],'image'=>url($p['image']),'sku'=>(string)$p['id'],'offers'=>['@type'=>'Offer','url'=>url('/products/'.$slug),'price'=>(int)$p['retail']*10,'priceCurrency'=>'IRR','availability'=>$p['stock']?'https://schema.org/InStock':'https://schema.org/OutOfStock','seller'=>['@type'=>'Organization','name'=>'نایلکس سادات']]]);
 json_ld(['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'خانه','item'=>url('/')],['@type'=>'ListItem','position'=>2,'name'=>$p['category_name'],'item'=>url(category_path(['id'=>$p['category_id'],'name'=>$p['category_name']]))],['@type'=>'ListItem','position'=>3,'name'=>$p['name'],'item'=>url('/products/'.$slug)]]]);
 ?><div class="container page-content"><nav class="breadcrumbs"><a href="/">خانه</a> / <a href="<?=h(category_path(['id'=>$p['category_id'],'name'=>$p['category_name']]))?>"><?=h($p['category_name'])?></a> / <?=h($p['name'])?></nav><div class="detail-grid"><div class="detail-image"><img src="<?=h($p['image'])?>" width="650" height="600" alt="<?=h($p['name'])?>"></div><div><span class="eyebrow"><?=h($p['category_name'])?></span><h1><?=h($p['name'])?></h1><h2>توضیحات محصول</h2><p class="detail-description"><?=nl2br(h($p['description']))?></p><div class="price-box"><span>قیمت خرده هر <?=h($p['unit'])?></span><strong><?=money($p['retail'])?> <small>تومان</small></strong><p>قیمت عمده <?=money($p['wholesale'])?> تومان، برای حداقل <?=money($p['minimum'])?> <?=h($p['unit'])?>.</p><?php if($approved):?><p>حساب عمده شما تأیید شده؛ قیمت عمده برای هر تعداد اعمال می‌شود.</p><?php endif;?></div><?php quantity_control($p,true);?><div class="product-stock-total"><span class="muted">موجودی <?=money($p['stock'])?> <?=h($p['unit'])?></span></div></div></div><?php product_seo_sections($p);?></div><?php page_footer();
}
function cart_page(bool $checkout): void {
 $lines=cart_lines();$sum=0;$invalid=false;foreach($lines as$l){if(!empty($l['missing'])){$invalid=true;continue;}$sum+=(int)$l['price']*$l['quantity'];if($l['quantity']>$l['stock'])$invalid=true;}$s=settings();$shipping=shipping_cost($sum,$s);
 page_header($checkout?'تکمیل سفارش':'سبد خرید','',false,url($checkout?'/checkout':'/cart'));?><div class="container page-content"><div class="page-heading"><h1><?=$checkout?'تکمیل سفارش':'سبد خرید شما'?></h1><span class="muted">سبد خرید ← اطلاعات ارسال ← پرداخت</span></div><?php if(!$lines):?><div class="empty-state"><h2>سبد خرید خالی است</h2><a class="btn" href="/products">مشاهده محصولات</a></div><?php else:?><div class="cart-layout"><div><?php if($checkout):$_SESSION['checkout_key']??=bin2hex(random_bytes(32));?><form method="post" id="checkout" class="panel form-stack" action="/checkout"><?php csrf_field();hidden('action','checkout');hidden('checkout_key',$_SESSION['checkout_key']);?><h2>اطلاعات گیرنده</h2><?php field('نام و نام خانوادگی','name',current_user()['name']??'');field('شماره موبایل','phone','','tel');textarea_field('نشانی کامل و کد پستی','address','',true);?><p class="muted">اطلاعات کارت فقط در صفحه درگاه وارد می‌شود.</p></form><?php else:?><div class="panel"><?php foreach($lines as$l):?><div class="cart-item"><?php if(!empty($l['missing'])):?><p>محصول دیگر در دسترس نیست.</p><?php else:?><img width="90" height="90" src="<?=h($l['image'])?>" alt="<?=h($l['name'])?>"><div class="cart-item-name"><?=h($l['name'])?><small><?=money($l['price'])?> تومان / <?=h($l['unit'])?></small></div><?php quantity_control($l);?><?php endif;action_start('cart_remove');hidden('id',$l['id']);?><button class="icon-button">حذف</button></form></div><?php endforeach;?></div><?php endif;?></div><aside class="panel order-summary"><h2>خلاصه سفارش</h2><p>مبلغ محصولات <b><?=money($sum)?> تومان</b></p><p>ارسال <b><?=$shipping?money($shipping).' تومان':'رایگان'?></b></p><?php if($s['free_above']):?><small>ارسال رایگان بالای <?=money($s['free_above'])?> تومان</small><?php endif;?><div class="summary-total"><span>مبلغ قابل پرداخت</span><strong><?=money($sum+$shipping)?> <small>تومان</small></strong></div><?php if($invalid):?><p class="error">موجودی بعضی محصولات کافی نیست؛ سبد را اصلاح کنید.</p><?php elseif($checkout):?><button form="checkout" class="btn">پرداخت و ثبت سفارش</button><?php else:?><a class="btn" href="/checkout">ادامه و تکمیل سفارش</a><?php endif;?><a href="/products" class="text-link">ادامه خرید</a></aside></div><?php endif;?></div><?php page_footer();
}
function auth_page(bool $register,bool $wholesale=false): void {
 if($signed=current_user()){
  page_header('حساب فعال','',false);?><div class="container page-content"><div class="panel form-stack auth-form"><h1>شما با حساب <?=h($signed['name'])?> وارد شده‌اید</h1><p>برای ورود یا ثبت‌نام با حساب دیگر، ابتدا از این حساب خارج شوید.</p><a class="btn" href="<?=$signed['role']==='ADMIN'?'/admin':'/account'?>">ادامه با حساب فعلی</a><?php action_start('switch_account','','/login');hidden('destination',$register?($wholesale?'/wholesale':'/register'):'/login');?><button class="btn outline">خروج و استفاده از حساب دیگر</button></form></div></div><?php page_footer();return;
 }
 $target=$register?($wholesale?'/wholesale':'/register'):'/login';
 page_header($register?'ساخت حساب کاربری':'ورود به حساب','',false,url($target));
 ?><div class="container page-content"><nav class="auth-tabs" aria-label="ورود و ثبت‌نام"><a href="/login" aria-current="<?=$register?'false':'page'?>">ورود به حساب موجود</a><a href="/register" aria-current="<?=$register?'page':'false'?>">ساخت حساب جدید</a></nav><?php action_start($register?'register':'login','panel form-stack auth-form',$target);?><h1><?=$register?($wholesale?'همکار نایلکس سادات شوید':'به خانواده نایلکس سادات بپیوندید'):'خوش آمدید'?></h1><p><?=$register?'خرید آسان‌تر، پیگیری سفارش‌ها و همراهی در هر خرید.':'برای ادامه خرید یا مدیریت فروشگاه وارد حساب خود شوید.'?></p><?php
 if($register){field('نام و نام خانوادگی','name');hidden('account_type',$wholesale?'wholesale':'retail');}
 ?><label><?=$register?'شماره موبایل':'نام کاربری / شماره موبایل'?><input name="username" value="<?=h($register?'':($_SESSION['login_username']??''))?>" required autocomplete="username" dir="ltr" <?=$register?'inputmode="tel" minlength="11" maxlength="11"':''?>></label><label>رمز عبور<?=$register?'؛ حداقل ۴ کاراکتر':''?><input name="password" type="password" required autocomplete="<?=$register?'new-password':'current-password'?>" <?=$register?'minlength="4"':''?>></label><a class="text-link" href="/forgot-password">&#128273; بازیابی رمز با پیامک</a><small>اطلاعات حساب و سابقه ورود برای مدیریت حساب و امنیت ذخیره می‌شود.</small><button class="btn"><?=$register?($wholesale?'ثبت درخواست حساب عمده':'ساخت حساب کاربری'):'ورود به حساب'?></button><a class="text-link" href="<?=$register?'/login':'/register'?>"><?=$register?'حساب دارید؟ وارد شوید':'حساب ندارید؟ ثبت‌نام کنید'?></a><?php if(!$wholesale):?><a class="text-link" href="/wholesale">ثبت درخواست همکاری عمده</a><?php endif;?></form></div><?php page_footer();
}
function account_page(): void {$u=current_user();if(!$u)redirect('/login');page_header('حساب کاربری','',false,url('/account'));?><div class="container page-content"><div class="panel account-panel"><h1>سلام، <?=h($u['name'])?></h1><p>حساب عمده: <?=h(['NONE'=>'عادی','PENDING'=>'در انتظار بررسی','APPROVED'=>'تأیید شده','REJECTED'=>'تأیید نشده'][$u['wholesale_status']])?></p><?php if($u['role']==='ADMIN'):?><a class="btn" href="/admin">پنل مدیریت</a><?php endif;?><h2>سفارش‌های شما</h2><?php foreach(all('SELECT code,status,total FROM ns_orders WHERE user_id=? ORDER BY id DESC LIMIT 30',[$u['id']])as$o):?><p><a href="/track?code=<?=h($o['code'])?>"><?=h($o['code'])?> · <?=h(order_status($o['status']))?></a></p><?php endforeach;action_start('logout');?><button class="btn outline">خروج از حساب</button></form><?php password_form();?></div></div><?php page_footer();}
function track_page(): void {page_header('پیگیری سفارش','',false,url('/track'));?><div class="container page-content track-wrap"><?php action_start('track','panel form-stack','/track');?><h1>پیگیری سفارش</h1><p>کد سفارش و موبایل گیرنده را وارد کنید.</p><?php if(isset($_GET['payment'])):?><p class="notice">از درگاه برگشتید؛ برای مشاهده نتیجه قطعی، اطلاعات سفارش را وارد کنید.</p><?php endif;field('کد سفارش','code',is_string($_GET['code']??null)?$_GET['code']:($_SESSION['last_order']??''));field('شماره موبایل','phone','','tel');?><button class="btn">بررسی سفارش</button></form><?php if(isset($_SESSION['tracked_order'])):$o=one('SELECT id,code,total,status,reference FROM ns_orders WHERE id=?',[$_SESSION['tracked_order']]);if($o):?><div class="panel tracking-result"><span class="status"><?=h(order_status($o['status']))?></span><h2><?=h($o['code'])?></h2><?php foreach(all('SELECT name,quantity,price FROM ns_order_items WHERE order_id=?',[$o['id']])as$i):?><p><?=h($i['name'])?> × <?=money($i['quantity'])?><b><?=money($i['price']*$i['quantity'])?> تومان</b></p><?php endforeach;?><p>مبلغ کل با ارسال <b><?=money($o['total'])?> تومان</b></p><?php if($o['reference']):?><p>شناسه پرداخت: <?=h($o['reference'])?></p><?php endif;?></div><?php endif;endif;?></div><?php page_footer();}
function info_page(string $path): void {$s=settings();$title=['/about'=>'درباره ما','/contact'=>'تماس با ما','/faq'=>'پرسش‌های متداول'][$path];page_header($title,$title.' نایلکس سادات؛ راهنمای خرید نایلون و نایلکس.',true,url($path));?><div class="container page-content"><article class="panel prose"><span class="eyebrow">نایلکس سادات</span><h1><?=h($title)?></h1><?php if($path==='/about'):?><h2>همراه خانه و کسب‌وکار شما</h2><?php if($s['company_about']):?><p><?=nl2br(h($s['company_about']))?></p><?php else:?><p>نایلکس سادات فروشگاه محصولات پلاستیکی و بسته‌بندی است. هدف ما ساده‌تر کردن تهیه نیازهای روزمره، با امکان خرید خرده و عمده و قیمت‌گذاری شفاف است.</p><p>کیسه فریزر، کیسه زباله، نایلون و نایلکس را بر اساس نیازتان انتخاب کنید. در هر محصول، حداقل تعداد خرید عمده مشخص شده است.</p><?php endif;?><a class="btn" href="/products">مشاهده محصولات</a><?php elseif($path==='/contact'):?><h2><?=h($s['company_name'])?></h2><?php foreach(['company_phone'=>'تلفن','company_email'=>'ایمیل','company_address'=>'نشانی','company_hours'=>'ساعات پاسخ‌گویی','company_postal_code'=>'کد پستی']as$k=>$v)if($s[$k])echo '<p>'.h($v).' : '.h($s[$k]).'</p>';if(!$s['company_phone']&&!$s['company_address'])echo '<p>اطلاعات تماس به‌زودی تکمیل می‌شود.</p>';?><a class="btn" href="/track">پیگیری سفارش</a><?php else:foreach(['چطور با قیمت عمده خرید کنم؟'=>'با رسیدن تعداد هر محصول به حداقل خرید عمده، قیمت همکاری اعمال می‌شود. مشتریان عمده تأییدشده برای هر تعداد از آن استفاده می‌کنند.','هزینه ارسال چقدر است؟'=>'هزینه ارسال ثابت و حد ارسال رایگان در سبد نمایش داده می‌شود.','پرداخت ناموفق شد؛ چه کنم؟'=>'کد سفارش را نگه دارید و وضعیت آن را در پیگیری بررسی کنید. برای بررسی تراکنش با پشتیبانی تماس بگیرید.']as$q=>$a):?><details><summary><?=h($q)?></summary><p><?=h($a)?></p></details><?php endforeach;endif;?></article></div><?php page_footer();}
