<?php
declare(strict_types=1);
function ensure_review_schema(): void {static $ready=false;if($ready)return;query("CREATE TABLE IF NOT EXISTS ns_reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,body VARCHAR(1500) NOT NULL,approved TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY product_user(product_id,user_id),INDEX(product_id,approved),FOREIGN KEY(product_id) REFERENCES ns_products(id),FOREIGN KEY(user_id) REFERENCES ns_users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$ready=true;}
function verified_buyer(int $userId,int $productId): bool {return one("SELECT o.id FROM ns_orders o JOIN ns_order_items i ON i.order_id=o.id WHERE o.user_id=? AND i.product_id=? AND o.status IN ('PAID','SHIPPED','DELIVERED') LIMIT 1",[$userId,$productId])!==null;}
function product_reviews(array $p): void {
 ensure_review_schema();$reviews=all("SELECT r.*,u.name FROM ns_reviews r JOIN ns_users u ON u.id=r.user_id WHERE r.product_id=? AND r.approved=1 ORDER BY r.id DESC LIMIT 50",[$p['id']]);
 ?><section class="panel seo-content" id="reviews"><h2>نظر خریداران</h2><?php if(!$reviews):?><p>هنوز نظر تأییدشده‌ای برای این محصول ثبت نشده است.</p><?php else:foreach($reviews as $review):?><article class="review"><p aria-label="<?=h($review['rating'])?> از ۵ ستاره"><?=str_repeat('★',(int)$review['rating'])?><?=str_repeat('☆',5-(int)$review['rating'])?></p><strong><?=h($review['name'])?></strong> <span class="verified-buyer">خریدار تأییدشده</span><time datetime="<?=h(substr($review['created_at'],0,10))?>"><?=h((new DateTimeImmutable($review['created_at'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Asia/Tehran'))->format('Y/m/d'))?></time><p><?=nl2br(h($review['body']))?></p></article><?php endforeach;endif;
 $u=current_user();if($u&&$u['role']==='CUSTOMER'&&verified_buyer((int)$u['id'],(int)$p['id'])):action_start('review','form-stack','/products/'.$p['slug']);hidden('id',$p['id']);?><h3>ثبت نظر درباره خرید</h3><label>امتیاز<select name="rating" required><?php foreach([5,4,3,2,1]as$r):?><option value="<?=$r?>"><?=$r?> ستاره</option><?php endforeach;?></select></label><label>نظر شما<textarea name="body" minlength="10" maxlength="1500" required></textarea></label><button class="btn">ارسال برای بررسی</button></form><?php elseif(!$u):?><a class="text-link" href="/login">برای ثبت نظر خرید وارد حساب شوید</a><?php endif;?></section><?php
}
