CREATE TABLE IF NOT EXISTS ns_categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_products (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(120) NOT NULL UNIQUE,
 name VARCHAR(180) NOT NULL,
 description TEXT NOT NULL,
 image VARCHAR(500) NOT NULL,
 retail INT UNSIGNED NOT NULL,
 wholesale INT UNSIGNED NOT NULL,
 minimum INT UNSIGNED NOT NULL DEFAULT 10,
 stock INT UNSIGNED NOT NULL DEFAULT 0,
 unit VARCHAR(30) NOT NULL DEFAULT 'بسته',
 featured TINYINT NOT NULL DEFAULT 0,
 active TINYINT NOT NULL DEFAULT 1,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 category_id BIGINT UNSIGNED NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES ns_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
 wholesale_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
 session_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_login_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 kind VARCHAR(30) NOT NULL,
 user_agent VARCHAR(300) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(created_at),
 FOREIGN KEY(user_id) REFERENCES ns_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code CHAR(23) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NULL,
 name VARCHAR(120) NOT NULL,
 phone VARCHAR(11) NOT NULL,
 address TEXT NOT NULL,
 total INT UNSIGNED NOT NULL,
 shipping INT UNSIGNED NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 authority CHAR(36) NULL UNIQUE,
 reference VARCHAR(100) NULL,
 checkout_key CHAR(64) NOT NULL UNIQUE,
 request_hash CHAR(64) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES ns_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_order_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL,
 product_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(180) NOT NULL,
 quantity INT UNSIGNED NOT NULL,
 price INT UNSIGNED NOT NULL,
 FOREIGN KEY(order_id) REFERENCES ns_orders(id),
 FOREIGN KEY(product_id) REFERENCES ns_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_settings (
 id TINYINT PRIMARY KEY,
 shipping INT UNSIGNED NOT NULL DEFAULT 45000,
 free_above INT UNSIGNED NOT NULL DEFAULT 2000000,
 company_name VARCHAR(120) NOT NULL DEFAULT 'نایلکس سادات',
 company_about TEXT NOT NULL,
 company_phone VARCHAR(25) NOT NULL DEFAULT '',
 company_email VARCHAR(150) NOT NULL DEFAULT '',
 company_address TEXT NOT NULL,
 company_hours VARCHAR(200) NOT NULL DEFAULT '',
 company_postal_code VARCHAR(10) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_rate_limits (
 id CHAR(64) PRIMARY KEY,
 attempts INT UNSIGNED NOT NULL,
 expires_at BIGINT UNSIGNED NOT NULL,
 INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
