CREATE TABLE IF NOT EXISTS ns_categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL UNIQUE,
 slug VARCHAR(120) NOT NULL DEFAULT '',
 parent_id BIGINT UNSIGNED NULL,
 sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 100,
 INDEX(parent_id,sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_category_migrations (
 `key` VARCHAR(80) PRIMARY KEY,
 completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_products (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(120) NOT NULL UNIQUE,
 name VARCHAR(180) NOT NULL,
 description TEXT NOT NULL,
 image VARCHAR(500) NOT NULL,
 retail INT UNSIGNED NOT NULL,
 wholesale INT UNSIGNED NOT NULL,
 minimum INT UNSIGNED NOT NULL DEFAULT 100,
 stock INT UNSIGNED NOT NULL DEFAULT 0,
 unit VARCHAR(30) NOT NULL DEFAULT 'بسته',
 featured TINYINT NOT NULL DEFAULT 0,
 active TINYINT NOT NULL DEFAULT 1,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 category_id BIGINT UNSIGNED NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES ns_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
 wholesale_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
 session_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_user_trash (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 original_user_id BIGINT UNSIGNED NOT NULL,
 username VARCHAR(100) NOT NULL,
 name VARCHAR(120) NOT NULL,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
 wholesale_status VARCHAR(20) NOT NULL DEFAULT 'NONE',
 session_version INT UNSIGNED NOT NULL DEFAULT 1,
 original_created_at DATETIME NOT NULL,
 deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 deleted_by BIGINT UNSIGNED NULL,
 INDEX(deleted_at),
 INDEX(username),
 FOREIGN KEY(deleted_by) REFERENCES ns_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_login_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 kind VARCHAR(30) NOT NULL,
 user_agent VARCHAR(300) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(created_at),
 FOREIGN KEY(user_id) REFERENCES ns_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code CHAR(23) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NULL,
 name VARCHAR(120) NOT NULL,
 phone VARCHAR(11) NOT NULL,
 address TEXT NOT NULL,
 total INT UNSIGNED NOT NULL,
 shipping INT UNSIGNED NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 authority CHAR(36) NULL UNIQUE,
 reference VARCHAR(100) NULL,
 checkout_key CHAR(64) NOT NULL UNIQUE,
 request_hash CHAR(64) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES ns_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_order_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL,
 product_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(180) NOT NULL,
 quantity INT UNSIGNED NOT NULL,
 price INT UNSIGNED NOT NULL,
 FOREIGN KEY(order_id) REFERENCES ns_orders(id),
 FOREIGN KEY(product_id) REFERENCES ns_products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_settings (
 id TINYINT PRIMARY KEY,
 shipping INT UNSIGNED NOT NULL DEFAULT 45000,
 free_above INT UNSIGNED NOT NULL DEFAULT 2000000,
 company_name VARCHAR(120) NOT NULL DEFAULT 'نایلکس سادات',
 company_about TEXT NOT NULL,
 company_phone VARCHAR(25) NOT NULL DEFAULT '09190385078',
 company_email VARCHAR(150) NOT NULL DEFAULT 'info@sadatpakhsh.ir',
 company_address TEXT NOT NULL,
 company_hours VARCHAR(200) NOT NULL DEFAULT '09:00 تا 17:00',
 company_postal_code VARCHAR(10) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_rate_limits (
 id CHAR(64) PRIMARY KEY,
 attempts INT UNSIGNED NOT NULL,
 expires_at BIGINT UNSIGNED NOT NULL,
 INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_articles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(120) NOT NULL UNIQUE,
 title VARCHAR(180) NOT NULL,
 excerpt VARCHAR(350) NOT NULL,
 body MEDIUMTEXT NOT NULL,
 image VARCHAR(500) NOT NULL,
 category_id BIGINT UNSIGNED NULL,
 active TINYINT(1) NOT NULL DEFAULT 1,
 published_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(active,published_at), INDEX(category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_content_blocks (`key` VARCHAR(120) PRIMARY KEY,label VARCHAR(180) NOT NULL,body TEXT NOT NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_admin_audit (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,action VARCHAR(80) NOT NULL,subject VARCHAR(180) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(created_at),FOREIGN KEY(user_id) REFERENCES ns_users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_reviews (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,body VARCHAR(1500) NOT NULL,approved TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY product_user(product_id,user_id),INDEX(product_id,approved),FOREIGN KEY(product_id) REFERENCES ns_products(id),FOREIGN KEY(user_id) REFERENCES ns_users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_product_features (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id BIGINT UNSIGNED NOT NULL,name VARCHAR(80) NOT NULL,value VARCHAR(180) NOT NULL,icon VARCHAR(30) NOT NULL DEFAULT 'other',sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,INDEX(product_id,sort_order),FOREIGN KEY(product_id) REFERENCES ns_products(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_product_seo (product_id BIGINT UNSIGNED PRIMARY KEY,seo_title VARCHAR(180) NOT NULL DEFAULT '',meta_description VARCHAR(350) NOT NULL DEFAULT '',focus_keyword VARCHAR(180) NOT NULL DEFAULT '',intro TEXT NOT NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES ns_products(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_analytics_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event VARCHAR(40) NOT NULL,path VARCHAR(300) NOT NULL,session_hash CHAR(64) NOT NULL,product_id BIGINT UNSIGNED NULL,order_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(event,created_at),INDEX(order_id),FOREIGN KEY(product_id) REFERENCES ns_products(id) ON DELETE SET NULL,FOREIGN KEY(order_id) REFERENCES ns_orders(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_admin_2fa (user_id BIGINT UNSIGNED PRIMARY KEY,secret_cipher TEXT NOT NULL,recovery_hashes TEXT NOT NULL,enabled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,last_counter BIGINT NOT NULL DEFAULT -1,FOREIGN KEY(user_id) REFERENCES ns_users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ns_slug_redirects (entity_type VARCHAR(20) NOT NULL,old_slug VARCHAR(120) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(entity_type,old_slug),INDEX(entity_type,target_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
