<?php
declare(strict_types=1);
require_once __DIR__.'/guides.php';
function category_profile(array $category): array {
 $name=$category['name'];
 $key=match(true){str_contains($name,'زباله')=>'trash-bags',str_contains($name,'فریزر')=>'freezer-bags',str_contains($name,'سفره')=>'tablecloth-rolls',str_contains($name,'ظروف')=>'disposable-tableware',str_contains($name,'بسته')=>'packaging',str_contains($name,'نایل')=>'shopping-bags',default=>'category-'.$category['id']};
 $content=match($key){
 'disposable-tableware'=>['ظروف یکبار مصرف پلاستیکی','خرید ظروف یکبار مصرف پلاستیکی عمده و خرده؛ مقایسه مدل‌های موجود، تعداد بسته و قیمت برای پذیرایی و مصرف فروشگاهی.','برای انتخاب ظروف، حجم، ابعاد و نوع مصرف را مشخص کنید. مناسب‌بودن برای غذای گرم یا سرد و تماس با مواد غذایی باید با مشخصات سازنده تطبیق داشته باشد.','برای سفارش عمده ظروف یکبار مصرف، تعداد هر نوع ظرف و زمان موردنیاز را اعلام کنید. قیمت نهایی و تعداد در کارتن را با اطلاعات هر محصول مقایسه کنید.'],
 'trash-bags'=>['نایلون و کیسه زباله','خرید کیسه زباله عمده و خرده؛ مدل‌های موجود را از نظر اندازه، رنگ، تعداد در بسته و قیمت مقایسه کنید. حداقل خرید عمده هر کالا در صفحه محصول مشخص است.','برای انتخاب نایلون زباله بزرگ یا کوچک، ابتدا اندازه سطل و نوع مصرف را مشخص کنید. تعداد کیسه در بسته و نوع بسته‌شدن کیسه را هم مقایسه کنید؛ قیمت بسته به‌تنهایی معیار مقایسه دو محصول نیست.','قیمت عمده کیسه زباله مشکی بزرگ به مشخصات همان محصول و تعداد سفارش وابسته است. قیمت و موجودی نمایش‌داده‌شده را در صفحه محصول بررسی کنید و پیش از سفارش ابعاد موردنیاز را با فروشگاه هماهنگ کنید.'],
 'freezer-bags'=>['کیسه فریزر یکبار مصرف','خرید کیسه فریزر عمده و خرده؛ مقایسه مدل‌های رولی و زیپ‌دار موجود، تعداد بسته و قیمت همکاری در نایلکس سادات.','در انتخاب کیسه فریزر، ابعاد قابل استفاده و روش بسته‌شدن کیسه را با نوع مصرف خود تطبیق دهید. برای مقایسه بسته‌ها، تعداد کیسه و واحد فروش را در کنار قیمت ببینید.','برای سفارش فروشگاهی، حداقل تعداد عمده هر محصول ملاک است. مناسب‌بودن برای تماس با مواد غذایی و شرایط نگهداری را از اطلاعات سازنده و مشخصات محصول بررسی کنید.'],
 'tablecloth-rolls'=>['سفره یکبار مصرف رولی','خرید سفره رولی یکبار مصرف؛ مشاهده طرح‌های موجود، واحد فروش و قیمت خرده و عمده برای خانه، رستوران و پذیرایی.','برای انتخاب سفره رولی، عرض میز و مقدار مصرف هر نوبت پذیرایی را مشخص کنید. طول رول، عرض سفره و تعداد رول در بسته از اطلاعات مهم برای مقایسه سفارش‌ها هستند.','برای سفارش عمده سفره رولی یکبار مصرف برای رستوران، تعداد موردنیاز و طرح دلخواه را اعلام کنید. پیش از نهایی‌کردن خرید، مشخصات و موجودی همان مدل را از فروشگاه بپرسید.'],
 'packaging'=>['نایلون بسته‌بندی','خرید نایلون بسته‌بندی عمده و خرده؛ بررسی محصولات موجود، قیمت واحد و حداقل تعداد سفارش همکاری در نایلکس سادات.','نایلون بسته‌بندی را بر اساس اندازه کالا، میزان شفافیت موردنیاز و روش بسته‌بندی انتخاب کنید. کاربرد صنعتی یا تماس با مواد غذایی باید با مشخصات اعلام‌شده محصول تطبیق داده شود.','هنگام استعلام نایلون بسته‌بندی عمده، ابعاد و ضخامت موردنیاز، مقدار مصرف و واحد خرید را مشخص کنید. اطلاعاتی که در صفحه درج نشده‌اند را قبل از پرداخت از فروشگاه تأیید بگیرید.'],
 'shopping-bags'=>['نایلون و نایلکس فروشگاهی','خرید نایلون و نایلکس عمده و خرده؛ مدل‌های موجود برای فروشگاه‌ها، قیمت واحد و شرایط خرید همکاری را مقایسه کنید.','برای انتخاب کیسه فروشگاهی، اندازه کالا، نوع دسته و مقدار مصرف روزانه را در نظر بگیرید. نایلون و نایلکس کاربردهای متفاوتی دارند؛ جنس و تحمل بار را بر اساس مشخصات واقعی هر کالا بررسی کنید.','برای خرید نایلون یکبار مصرف برای فروشگاه‌ها، تعداد موردنیاز را در صفحه محصول انتخاب کنید. با رسیدن به حداقل تعداد تعیین‌شده، قیمت عمده همان محصول اعمال می‌شود.'],
 default=>[$name,'مشاهده محصولات '.$name.'، قیمت خرده، قیمت عمده و موجودی در نایلکس سادات.','مشخصات و واحد فروش محصولات این دسته را پیش از خرید مقایسه کنید.','قیمت عمده با رسیدن به حداقل تعداد مشخص‌شده در صفحه هر محصول اعمال می‌شود.'],
 };
 // Preserve meaningful subtype names instead of giving all matching categories the same title.
 $general=['کیسه زباله','نایلون زباله','کیسه فریزر','سفره یکبار مصرف','بسته‌بندی','نایلون و نایلکس','ظروف یکبار مصرف','ظروف یکبار مصرف پلاستیکی'];
 if(!in_array($name,$general,true)){$content[0]=$name;$content[1]='خرید '.$name.' عمده و خرده؛ مقایسه مدل‌های موجود، واحد فروش، قیمت و حداقل سفارش در نایلکس سادات.';}
 return ['key'=>$key,'path'=>'/categories/'.$category['id'].'-'.$key,'label'=>$content[0],'description'=>$content[1],'guide'=>$content[2],'wholesale'=>$content[3]];
}
function seo_categories(): array {return all('SELECT c.* FROM ns_categories c WHERE EXISTS (SELECT 1 FROM ns_products p WHERE p.category_id=c.id AND p.active=1) ORDER BY c.id');}
function category_path(array $category): string {return category_profile($category)['path'];}
function category_page(string $path): bool {
 $category=null;
 if(preg_match('#^/categories/([1-9][0-9]*)-[a-z0-9-]+$#',$path,$match))$category=one('SELECT * FROM ns_categories WHERE id=?',[$match[1]]);
 if(!$category)return false;
 if(category_path($category)!==$path)redirect(category_path($category),301);
 $profile=category_profile($category);$products=all('SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND p.category_id=? ORDER BY p.id DESC LIMIT 100',[$category['id']]);
 $heading='خرید '.$profile['label'].' — عمده و خرده';
 page_header($heading,$profile['description'],(bool)$products,url($path));
 json_ld(['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>$heading,'description'=>$profile['description'],'url'=>url($path),'mainEntity'=>['@type'=>'ItemList','itemListElement'=>array_map(fn($p,$i)=>['@type'=>'ListItem','position'=>$i+1,'url'=>url('/products/'.$p['slug'])],$products,array_keys($products))]]);
 json_ld(['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'خانه','item'=>url('/')],['@type'=>'ListItem','position'=>2,'name'=>$category['name'],'item'=>url($path)]]]);
 ?><div class="container page-content"><nav class="breadcrumbs"><a href="/">خانه</a> ← <a href="/products">محصولات</a> ← <?=h($category['name'])?></nav><h1><?=h($heading)?></h1><?php editable_text('category.'.$category['id'].'.description','معرفی دسته',$profile['description']);?><section><h2>انواع <?=h($profile['label'])?></h2><div class="product-grid"><?php foreach($products as $p)product_card($p);?></div><?php if(!$products):?><p>در حال حاضر محصول فعالی در این دسته وجود ندارد.</p><?php endif;?></section><section class="panel seo-content"><h2>مشخصات فنی و راهنمای انتخاب</h2><?php editable_text('category.'.$category['id'].'.guide','راهنمای دسته',$profile['guide']);?><h3>اندازه، تعداد و واحد فروش</h3><p>مشخصات دقیق هر مدل را در صفحه همان محصول ببینید. برای ابعاد، وزن یا جنسی که درج نشده است، قبل از خرید از پشتیبانی سؤال کنید.</p><h2>قیمت عمده</h2><?php editable_text('category.'.$category['id'].'.wholesale','شرایط عمده دسته',$profile['wholesale']);?><p>برای همه مشتریان، با رسیدن تعداد هر کالا به آستانه درج‌شده در صفحه محصول، قیمت عمده خودکار اعمال می‌شود. هزینه ارسال پیش از پرداخت در سبد نمایش داده می‌شود.</p><a class="btn" href="/wholesale">خرید عمده</a> <a class="text-link" href="/contact">استعلام مشخصات و سفارش</a></section><?php visible_faq(category_questions($category),'پرسش‌های خرید '.$category['name']);guide_cards(guides_for_category($category));?></div><?php page_footer();return true;
}
function category_questions(array $category): array {
 $profile=category_profile($category);
 return [
 ['question'=>'برای انتخاب '.$category['name'].' چه مشخصاتی را مقایسه کنم؟','answer'=>$profile['guide']],
  ['question'=>'حداقل سفارش عمده این دسته چقدر است؟','answer'=>'حداقل خرید برای هر محصول جداگانه و بر اساس واحد فروش آن تعیین می‌شود. تعداد و قیمت عمده را در صفحه همان کالا ببینید؛ با رسیدن به حد نصاب، قیمت عمده خودکار اعمال می‌شود.'],
 ['question'=>'قیمت و هزینه ارسال را کجا ببینم؟','answer'=>'قیمت هر مدل در صفحه محصول نمایش داده می‌شود. پس از انتخاب تعداد، مبلغ کالاها و هزینه ارسال در سبد خرید مشخص است؛ مبلغ نهایی را پیش از پرداخت بررسی کنید.'],
 ];
}
function product_seo_sections(array $p): void {$profile=category_profile(['id'=>$p['category_id'],'name'=>$p['category_name']]);?>
 <section class="panel seo-content"><h2>راهنمای خرید <?=h($p['name'])?></h2><p><?=h($profile['guide'])?></p><h3>پیش از نهایی‌کردن سفارش</h3><ul class="product-checklist"><li>واحد فروش این کالا «<?=h($p['unit'])?>» است؛ قیمت‌ها را با محصولی دارای واحد یکسان مقایسه کنید.</li><li><?php if(is_wholesale_product($p)):?>قیمت درج‌شدهٔ این کالا، قیمت عمده است و برای همهٔ مشتریان اعمال می‌شود.<?php else:?>برای فعال‌شدن قیمت عمده، تعداد همین کالا باید به <?=money($p['minimum'])?> <?=h($p['unit'])?> برسد.<?php endif;?></li><li>ویژگی‌های ثبت‌شده، توضیحات محصول و موجودی را بررسی کنید و مشخصات درج‌نشده را پیش از پرداخت استعلام بگیرید.</li><li><a href="<?=h(category_path(['id'=>$p['category_id'],'name'=>$p['category_name']]))?>">مدل‌های دیگر <?=h($p['category_name'])?></a> را برای مقایسه ببینید.</li></ul></section>
 <?php article_cards(articles_for_category((int)$p['category_id'],6),'مقاله‌های مرتبط با '.$p['category_name']);?>
 <section class="panel seo-content"><h2>مشخصات محصول</h2><table><tbody><?php foreach((is_wholesale_product($p)?['دسته‌بندی'=>$p['category_name'],'واحد فروش'=>$p['unit'],'قیمت عمده'=>money($p['wholesale']).' تومان']:['دسته‌بندی'=>$p['category_name'],'واحد فروش'=>$p['unit'],'حداقل خرید عمده'=>money($p['minimum']).' '.$p['unit'],'قیمت خرده'=>money($p['retail']).' تومان','قیمت عمده'=>money($p['wholesale']).' تومان']) as $label=>$value):?><tr><th scope="row"><?=h($label)?></th><td><?=h($value)?></td></tr><?php endforeach;?></tbody></table><h3>ابعاد، وزن و جنس</h3><p>برای این مشخصات به توضیحات همین محصول مراجعه کنید؛ موارد درج‌نشده را پیش از سفارش از فروشگاه استعلام بگیرید.</p><h2>قیمت عمده و نحوه سفارش</h2><p><?php product_sales_hint($p);?> قیمت نهایی و موجودی را هنگام تکمیل خرید در سبد بررسی کنید.</p><p>برای هماهنگی سفارش فروشگاهی، <a href="/wholesale-buying">شرایط خرید عمده</a> را ببینید.</p></section>
 <?php visible_faq([['question'=>'آیا '.$p['name'].' موجود است؟','answer'=>$p['stock']?'این محصول اکنون موجود است؛ تعداد قابل سفارش و قیمت را در همین صفحه بررسی کنید.':'این محصول اکنون ناموجود است؛ برای زمان تأمین با فروشگاه تماس بگیرید.'],['question'=>'قیمت عمده این محصول از چه تعدادی اعمال می‌شود؟','answer'=>is_wholesale_product($p)?'این محصول با قیمت عمدهٔ درج‌شده برای همهٔ مشتریان قابل خرید است؛ ورود به حساب لازم نیست.':'از '.money($p['minimum']).' '.$p['unit'].' قیمت عمده برای همین محصول به‌صورت خودکار اعمال می‌شود و تأیید حساب جداگانه لازم نیست.']],'پرسش‌های خرید این محصول');?><p class="product-next-links"><a href="<?=h(category_path(['id'=>$p['category_id'],'name'=>$p['category_name']]))?>">همه محصولات <?=h($p['category_name'])?></a> · <a href="/wholesale">خرید عمده</a> · <a href="/faq">پرسش‌های متداول</a></p><?php guide_cards(guides_for_category(['id'=>$p['category_id'],'name'=>$p['category_name']]));
$related=all('SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND p.unit=? AND p.category_id<>? AND p.id<>? ORDER BY p.featured DESC,p.id DESC LIMIT 4',[$p['unit'],$p['category_id'],$p['id']]);product_recommendations('محصولات مشابه',$related);
 $categoryItems=all('SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND p.category_id=? AND p.id<>? ORDER BY p.stock DESC,p.id DESC LIMIT 4',[$p['category_id'],$p['id']]);product_recommendations('محصولات این دسته',$categoryItems);
$bought=all("SELECT p.*,c.name category_name,SUM(i.quantity) sold FROM ns_order_items source JOIN ns_orders o ON o.id=source.order_id JOIN ns_order_items i ON i.order_id=o.id AND i.product_id<>source.product_id JOIN ns_products p ON p.id=i.product_id AND p.active=1 JOIN ns_categories c ON c.id=p.category_id WHERE source.product_id=? AND o.status IN ('PAID','SHIPPED','DELIVERED') GROUP BY p.id,c.name ORDER BY sold DESC LIMIT 4",[$p['id']]);if(!$bought)$bought=all("SELECT p.*,c.name category_name,COALESCE(SUM(CASE WHEN o.id IS NOT NULL THEN i.quantity ELSE 0 END),0) sold FROM ns_products p JOIN ns_categories c ON c.id=p.category_id LEFT JOIN ns_order_items i ON i.product_id=p.id LEFT JOIN ns_orders o ON o.id=i.order_id AND o.status IN ('PAID','SHIPPED','DELIVERED') WHERE p.active=1 AND p.id<>? GROUP BY p.id,c.name ORDER BY sold DESC,p.featured DESC,p.id DESC LIMIT 4",[$p['id']]);product_recommendations('محصولات پرفروش',$bought);
 $wholesale=all('SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND EXISTS (SELECT 1 FROM ns_product_sales sales WHERE sales.product_id=p.id AND sales.sale_type=\'wholesale\') AND p.id<>? ORDER BY (p.retail-p.wholesale) DESC,p.id DESC LIMIT 4',[$p['id']]);product_recommendations('مناسب خرید عمده',$wholesale);
}
function product_recommendations(string $heading,array $items): void {if(!$items)return;?><section class="seo-content product-recommendations"><h2><?=h($heading)?></h2><div class="product-grid"><?php foreach($items as $item)product_card($item);?></div></section><?php }
