<?php
declare(strict_types=1);
require_once __DIR__.'/icons.php';
require_once __DIR__.'/seo.php';
function brand(): void {echo '<a class="brand" href="/"><span class="brand-symbol">'.icon('box').'</span><span>نایلکس <b>سادات</b><small>SADAT NYLEX</small></span></a>';}
function page_header(string $title,string $description='',bool $index=true,string $canonical='',string $shareImage='',string $ogType='website'): void {
 global $nonce;$s=settings();$u=current_user();$fullTitle=str_starts_with($title,'نایلکس سادات _')?$title:$title.' | نایلکس سادات';$description=$description?:'خرید خرده و عمده نایلون، نایلکس، کیسه فریزر و کیسه زباله از نایلکس سادات.';if(!$index)header('X-Robots-Tag: noindex, follow');$canonical=$canonical?:url('/');$shareImage=$shareImage?:url('/assets/social-cover.png');
 ?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($fullTitle)?></title><meta name="description" content="<?=h($description)?>"><meta name="robots" content="<?=$index?'index,follow':'noindex,follow'?>"><link rel="canonical" href="<?=h($canonical)?>"><meta property="og:title" content="<?=h($fullTitle)?>"><meta property="og:description" content="<?=h($description)?>"><meta property="og:url" content="<?=h($canonical)?>"><meta property="og:type" content="<?=h($ogType)?>"><meta property="og:locale" content="fa_IR"><meta property="og:image" content="<?=h($shareImage)?>"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/icon.svg"><link rel="stylesheet" href="<?=h(asset_url('shop.css'))?>"><script src="<?=h(asset_url('shop.js'))?>" defer nonce="<?=h($nonce)?>"></script></head><body><a href="#main-content" class="skip-link">رفتن به محتوای اصلی</a>
 <?php $org=['@context'=>'https://schema.org','@type'=>'Organization','name'=>'نایلکس سادات','legalName'=>$s['company_name'],'url'=>url('/'),'logo'=>url('/assets/icon.svg')];if($s['company_phone'])$org['telephone']=$s['company_phone'];if($s['company_email'])$org['email']=$s['company_email'];if($s['company_address'])$org['address']=['@type'=>'PostalAddress','streetAddress'=>$s['company_address'],'addressCountry'=>'IR','postalCode'=>$s['company_postal_code']];json_ld($org);?>
 <div class="announcement"><span>از خانه تا کسب‌وکار، همراه همیشگی شما</span><span>خرید مستقیم، کیفیت مطمئن</span></div><header class="header"><div class="container header-main"><?php brand();?><form action="/products" class="search"><?=icon('search')?><input name="q" placeholder="دنبال چه محصولی می‌گردید؟" aria-label="جستجو" autocomplete="off" data-product-search><div class="search-suggestions" data-search-suggestions hidden role="listbox" aria-label="پیشنهاد محصولات"></div><button>جستجو</button></form><div class="header-actions"><a class="account-link" href="<?=$u?'/account':'/login'?>"><?=icon('user')?><span><?=$u?h($u['name']):'ورود / ثبت‌نام'?></span></a><i></i><?php cart_preview();?><button class="mobile-menu" type="button" data-menu aria-label="فهرست" aria-expanded="false"><?=icon('menu')?></button></div></div><nav class="container nav"><a class="nav-category" href="/products"><?=icon('menu')?> دسته‌بندی محصولات</a><a href="/">صفحه اصلی</a><a href="/products">همه محصولات</a><a href="/wholesale-buying">خرید عمده <span class="tiny-label">ویژه همکاران</span></a><a href="/guides">راهنمای خرید</a><a href="/track">پیگیری سفارش</a><a href="/about">درباره ما</a><a href="/contact">تماس با ما</a><?php if($u&&$u['role']==='ADMIN'):?><a href="/admin">مدیریت</a><?php endif;?></nav></header><main id="main-content">
 <?php if(isset($_SESSION['flash'])):[$kind,$message]=$_SESSION['flash'];unset($_SESSION['flash']);?><div class="container"><p class="<?=h($kind)?>" role="status"><?=h($message)?></p></div><?php endif;
}
function page_footer(): void {$s=settings();?></main><footer><div class="container footer-main"><div><?php brand();?><p>کیفیت در جزئیات، آسودگی در زندگی.<br>تأمین محصولات پلاستیکی برای خانه و کسب‌وکار شما.</p></div><div><h4>دسترسی سریع</h4><a href="/products">فروشگاه محصولات</a><a href="/wholesale-buying">همکاری و خرید عمده</a><a href="/guides">راهنمای خرید محصولات</a><a href="/articles">مقاله‌ها</a><a href="/about">درباره نایلکس سادات</a></div><div><h4>راهنمای مشتریان</h4><a href="/track">پیگیری سفارش</a><a href="/contact">تماس و پشتیبانی</a><a href="/faq">پرسش‌های متداول</a></div><div class="footer-note"><h4><?=h($s['company_name'])?></h4><?php if($s['company_phone']):?><a dir="ltr" href="tel:<?=h(preg_replace('/[ ()-]/','',$s['company_phone']))?>"><?=h($s['company_phone'])?></a><?php endif;?><p><?=h($s['company_address'])?></p></div></div><div class="container copyright"><span>تمامی حقوق برای نایلکس سادات محفوظ است.</span><span>با دقت انتخاب کنید، با خیال راحت خرید کنید.</span></div></footer></body></html><?php }
function action_start(string $action,string $class='',string $target=''): void {echo '<form method="post" action="'.h($target?:'/'). '" class="'.h($class).'">';csrf_field();if($action==='cart_add')echo '<span class="product-cart-quantity" data-product-count aria-live="polite"></span>';echo '<input type="hidden" name="action" value="'.h($action).'">';}
function hidden(string $name,mixed $value): void {echo '<input type="hidden" name="'.h($name).'" value="'.h($value).'">';}
function product_card(array $p): void { ?><article class="product-card"><a class="product-image" href="/products/<?=h($p['slug'])?>"><span class="product-badge">قیمت عمده و خرده</span><img src="<?=h($p['image'])?>" alt="<?=h($p['name'])?>" width="350" height="280" loading="lazy"></a><div class="product-body"><span class="muted product-category"><?=h($p['category_name']??'محصولات')?></span><a href="/products/<?=h($p['slug'])?>"><h3><?=h($p['name'])?></h3></a><div class="product-meta"><span><?=$p['stock']?'موجود در انبار':'ناموجود'?></span><span>هر <?=h($p['unit'])?></span></div><div class="product-bottom"><div><small>قیمت مصرف‌کننده</small><strong><?=money($p['retail'])?> <span>تومان</span></strong></div><?php quantity_control($p);?></div><div class="wholesale-hint">خرید <?=money($p['minimum'])?> <?=h($p['unit'])?> و بیشتر با قیمت همکاری</div></div></article><?php }
function password_form(): void {action_start('password','panel form-stack','/account');?><h2>تغییر رمز عبور</h2><?php field('رمز فعلی','current_password','','password');field('رمز جدید، حداقل ۴ کاراکتر','new_password','','password');?><button class="btn">تغییر رمز و بستن نشست‌های قبلی</button></form><?php }

function quantity_control(array $p,bool $initialButton=false): void {
 $qty=(int)($_SESSION['cart'][$p['id']]??0);$max=min(1000,(int)$p['stock']);
 ?><form method="post" action="/" class="quantity-control" data-quantity-control data-max="<?=$max?>" data-qty="<?=$qty?>">
 <?php csrf_field();hidden('id',$p['id']);hidden('quantity',1);?>
 <?php if($initialButton):?><button type="submit" name="action" value="cart_add" class="btn" data-first-add <?=$qty?'hidden':''?> <?=$max>0?'':'disabled'?>><?=$max>0?'افزودن به سبد خرید':'ناموجود'?></button><?php endif;?>
 <div class="quantity-stepper" <?=$initialButton&&$qty===0?'hidden':''?> role="group" aria-label="تعداد <?=h($p['name'])?>">
 <button type="submit" name="action" value="cart_decrease" data-minus aria-label="کاهش تعداد <?=h($p['name'])?>" <?=$qty?'':'disabled'?>>−</button>
 <output data-product-count aria-live="polite" aria-label="تعداد انتخاب‌شده"><?=money($qty)?></output>
 <button type="submit" name="action" value="cart_add" data-plus aria-label="افزایش تعداد <?=h($p['name'])?>" <?=$qty<$max?'':'disabled'?>>+</button>
 </div><span data-cart-message role="status"></span></form><?php
}
