<?php
declare(strict_types=1);
require_once __DIR__.'/icons.php';
require_once __DIR__.'/seo.php';
function brand(): void {echo '<a class="brand" href="/" aria-label="نایلکس سادات؛ صفحه اصلی"><img src="/assets/logo.png" width="48" height="48" alt="" style="border-radius:12px"><span>نایلکس <b>سادات</b><small>SADAT NYLEX</small></span></a>';}
function category_mega_menu(): void {
 $tree=category_tree();?>
 <div class="nav-category-wrap"><button class="nav-category" type="button" aria-expanded="false" aria-controls="category-mega" data-category-toggle><?=icon('menu')?> دسته‌بندی محصولات</button><div class="category-mega" id="category-mega"><div class="category-mega-grid"><?php foreach($tree as$parent):?><section><strong class="category-parent"><?=h($parent['name'])?></strong><div class="category-sale-links"><a href="/products?category=<?=$parent['id']?>">خرید خرد</a><a href="/wholesale?category=<?=$parent['id']?>">خرید عمده</a></div><?php if($parent['children']):?><ul><?php foreach($parent['children'] as$child):?><li><span><?=h($child['name'])?></span><span class="category-sale-links"><a href="/products?category=<?=$child['id']?>">خرد</a><a href="/wholesale?category=<?=$child['id']?>">عمده</a></span></li><?php endforeach;?></ul><?php endif;?></section><?php endforeach;?></div><div class="category-all"><a href="/products">همه محصولات خرد</a><a href="/wholesale">همه محصولات عمده</a></div></div></div>
 <?php }
function page_header(string $title,string $description='',bool $index=true,string $canonical='',string $shareImage='',string $ogType='website'): void {
 global $nonce;$s=settings();$u=current_user();$fullTitle=str_starts_with($title,'نایلکس سادات _')?str_replace('نایلکس سادات _','نایلکس سادات |',$title):$title.' | نایلکس سادات';$description=$description?:'خرید خرده و عمده محصولات پلاستیکی، نایلون، نایلکس، کیسه فریزر و کیسه زباله از نایلکس سادات؛ پلاستیک سادات و سادات پخش.';if(!$index)header('X-Robots-Tag: noindex, follow');$canonical=$canonical?:url('/');$shareImage=$shareImage?:url('/assets/social-cover.png');
 ?><!doctype html><html lang="fa-IR" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($fullTitle)?></title><meta name="description" content="<?=h($description)?>"><meta name="robots" content="<?=$index?'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1':'noindex,follow'?>"><link rel="canonical" href="<?=h($canonical)?>"><link rel="alternate" hreflang="fa-IR" href="<?=h($canonical)?>"><meta property="og:title" content="<?=h($fullTitle)?>"><meta property="og:description" content="<?=h($description)?>"><meta property="og:url" content="<?=h($canonical)?>"><meta property="og:type" content="<?=h($ogType)?>"><meta property="og:locale" content="fa_IR"><meta property="og:site_name" content="نایلکس سادات"><meta property="og:image" content="<?=h($shareImage)?>"><meta property="og:image:alt" content="نایلکس سادات؛ فروش محصولات پلاستیکی"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon-96.png"><link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"><link rel="stylesheet" href="<?=h(asset_url('shop.css'))?>"><?php if($canonical===url('/')&&$index):?><link rel="stylesheet" href="<?=h(asset_url('home-experience.css'))?>"><?php endif;?><script src="<?=h(asset_url('shop.js'))?>" defer nonce="<?=h($nonce)?>"></script><?php if($canonical===url('/')&&$index):?><script src="<?=h(asset_url('home-experience.js'))?>" defer nonce="<?=h($nonce)?>"></script><?php endif;?></head><body><a href="#main-content" class="skip-link">رفتن به محتوای اصلی</a>
 <?php $org=['@context'=>'https://schema.org','@type'=>'Organization','name'=>'نایلکس سادات','alternateName'=>['پلاستیک سادات','سادات پخش','بازرگانی سادات پخش'],'legalName'=>$s['company_name'],'description'=>'تولید و فروش مستقیم عمده و خرده نایلکس و محصولات پلاستیکی در تهران برای بازار سراسر ایران','url'=>url('/'),'areaServed'=>['@type'=>'Country','name'=>'ایران'],'logo'=>['@type'=>'ImageObject','url'=>url('/assets/logo.png')]];if($s['company_phone'])$org['telephone']=$s['company_phone'];if($s['company_email'])$org['email']=$s['company_email'];$org['address']=['@type'=>'PostalAddress','addressLocality'=>'تهران','addressCountry'=>'IR'];if($s['company_address'])$org['address']['streetAddress']=$s['company_address'];if($s['company_postal_code'])$org['address']['postalCode']=$s['company_postal_code'];json_ld($org);?>
 <div class="announcement"><span>از خانه تا کسب‌وکار، همراه همیشگی شما</span><span>خرید مستقیم، کیفیت مطمئن</span></div><header class="header"><div class="container header-main"><?php brand();?><form action="/search" class="search"><?=icon('search')?><input name="q" placeholder="دنبال چه محصولی می‌گردید؟" aria-label="جستجو" autocomplete="off" data-product-search><div class="search-suggestions" data-search-suggestions hidden role="listbox" aria-label="پیشنهاد محصولات"></div><button>جستجو</button></form><div class="header-actions"><a class="account-link" href="<?=$u?'/account':'/login'?>"><?=icon('user')?><span><?=$u?h($u['name']):'ورود / ثبت‌نام'?></span></a><i></i><?php cart_preview();?><button class="mobile-menu" type="button" data-menu aria-label="فهرست" aria-expanded="false"><?=icon('menu')?></button></div></div><nav class="container nav"><?php category_mega_menu();?><a href="/">صفحه اصلی</a><a href="/products">فروش خرد</a><a href="/wholesale">فروش عمده</a><a href="/guides">راهنمای خرید</a><a href="/nylex-manufacturer">تولیدکننده نایلکس</a><a href="/about">درباره ما</a><a href="/contact">تماس با ما</a><?php if($u&&$u['role']==='ADMIN'):?><a href="/admin">مدیریت</a><?php endif;?></nav></header><main id="main-content">
 <?php if(isset($_SESSION['flash'])):[$kind,$message]=$_SESSION['flash'];unset($_SESSION['flash']);?><div class="container"><p class="<?=h($kind)?>" role="status"><?=h($message)?></p></div><?php endif;
}
function page_footer(): void {$s=settings();$wa=digits(content_text('company.whatsapp',''));if(str_starts_with($wa,'0'))$wa='98'.substr($wa,1);?></main><footer><div class="container footer-main"><div><?php brand();?><p>تولید و فروش مستقیم محصولات نایلکس و پلاستیکی برای خانه و کسب‌وکار؛ تهران و سراسر ایران.</p></div><div><h4>دسترسی سریع</h4><a href="/products">فروش خرد</a><a href="/wholesale">فروش عمده</a><a href="/nylex-manufacturer">تولیدکننده نایلکس</a><a href="/guides">راهنمای خرید</a><a href="/about">درباره نایلکس سادات</a></div><div><h4>راهنمای مشتریان</h4><a href="/track">پیگیری سفارش</a><a href="/shipping">روش‌های ارسال</a><a href="/contact">تماس و پشتیبانی</a><a href="/faq">پرسش‌های متداول</a><a href="/privacy">حریم خصوصی</a></div><div class="footer-note"><h4><?=h($s['company_name'])?></h4><?php if($s['company_phone']):?><a dir="ltr" href="tel:<?=h(preg_replace('/[ ()-]/','',$s['company_phone']))?>"><?=h($s['company_phone'])?></a><?php endif;?><p><?=h($s['company_address'])?></p><?php if($s['company_hours']):?><p><?=h($s['company_hours'])?></p><?php endif;?></div></div><div class="container copyright"><span>تمامی حقوق برای نایلکس سادات محفوظ است.</span><span>با دقت انتخاب کنید، با خیال راحت خرید کنید.</span></div></footer><?php if($wa):?><a class="whatsapp-cta" href="https://wa.me/<?=h($wa)?>?text=<?=rawurlencode('سلام، برای خرید عمده مشاوره می‌خواهم.')?>" target="_blank" rel="noopener noreferrer">مشاوره خرید عمده در واتساپ</a><?php endif;?></body></html><?php }
function action_start(string $action,string $class='',string $target=''): void {echo '<form method="post" action="'.h($target?:'/'). '" class="'.h($class).'">';csrf_field();if($action==='cart_add')echo '<span class="product-cart-quantity" data-product-count aria-live="polite"></span>';echo '<input type="hidden" name="action" value="'.h($action).'">';}
function hidden(string $name,mixed $value): void {echo '<input type="hidden" name="'.h($name).'" value="'.h($value).'">';}
function product_card(array $p,string $context=''): void {$wholesaleView=$context==='wholesale';$explicitWholesale=is_wholesale_product($p);?><article class="product-card"><a class="product-image" href="/products/<?=h($p['slug'])?>"><span class="product-badge"><?=$wholesaleView||$explicitWholesale?'محصول عمده':'محصول خرده'?></span><img src="<?=h($p['image'])?>" alt="<?=h($p['name'])?>؛ <?=h($p['category_name']??'محصولات پلاستیکی')?>" width="350" height="280" loading="lazy" decoding="async" sizes="(max-width: 560px) 46vw, (max-width: 900px) 44vw, 350px"></a><div class="product-body"><span class="muted product-category"><?=h($p['category_name']??'محصولات')?></span><a href="/products/<?=h($p['slug'])?>"><h3><?=h($p['name'])?></h3></a><div class="product-meta"><span><?=$p['stock']?'موجود در انبار':'ناموجود'?></span><span>هر <?=h($p['unit'])?></span></div><div class="product-bottom"><div><small><?=$wholesaleView||$explicitWholesale?'قیمت عمده':'قیمت خرده'?></small><strong><?=money($wholesaleView?(int)$p['wholesale']:unit_price($p,1))?> <span>تومان</span></strong></div><?php if($wholesaleView&&!$explicitWholesale):?><a class="btn outline" href="/products/<?=h($p['slug'])?>">انتخاب تعداد</a><?php else:quantity_control($p);endif;?></div><div class="wholesale-hint"><?php if($wholesaleView&&!$explicitWholesale):?>قیمت عمده از <?=money($p['minimum'])?> <?=h($p['unit'])?>؛ تعداد را در صفحه محصول وارد کنید.<?php else:product_sales_hint($p);endif;?></div></div></article><?php }
function password_form(): void {action_start('password','panel form-stack','/account');?><h2>تغییر رمز عبور</h2><?php field('رمز فعلی','current_password','','password');?><label>رمز جدید، حداقل ۸ کاراکتر<input name="new_password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label><button class="btn">تغییر رمز و بستن نشست‌های قبلی</button></form><?php }

function quantity_control(array $p,bool $initialButton=false): void {
 $qty=(int)($_SESSION['cart'][$p['id']]??0);$max=min(1000,(int)$p['stock']);
 ?><form method="post" action="/" class="quantity-control" data-quantity-control data-max="<?=$max?>" data-qty="<?=$qty?>">
 <?php csrf_field();hidden('id',$p['id']);hidden('quantity',1);?>
 <?php if($initialButton):?><button type="submit" name="action" value="cart_add" class="btn" data-first-add <?=$qty?'hidden':''?> <?=$max>0?'':'disabled'?>><?=$max>0?'افزودن به سبد خرید':'ناموجود'?></button><?php endif;?>
 <div class="quantity-stepper" <?=$initialButton&&$qty===0?'hidden':''?> role="group" aria-label="تعداد <?=h($p['name'])?>">
 <button type="submit" name="action" value="cart_decrease" data-minus aria-label="کاهش تعداد <?=h($p['name'])?>" <?=$qty?'':'disabled'?>>−</button>
 <output data-product-count aria-live="polite" aria-label="تعداد انتخاب‌شده"><?=money($qty)?></output>
 <button type="submit" name="action" value="cart_add" data-plus aria-label="افزایش تعداد <?=h($p['name'])?>" <?=$qty<$max?'':'disabled'?>>+</button>
 </div><div class="quantity-entry"><label>تعداد <?=h($p['unit'])?><input type="number" name="requested_quantity" data-quantity-input min="1" max="<?=max(1,$max)?>" value="<?=max(1,$qty)?>" inputmode="numeric" <?=$max?'':'disabled'?>></label><button type="submit" name="action" value="cart_set" class="btn outline" <?=$max?'':'disabled'?>>ثبت تعداد</button></div><small data-current-price>قیمت فعلی هر <?=h($p['unit'])?>: <?=money(unit_price($p,max(1,$qty)))?> تومان</small><span data-cart-message role="status"></span></form><?php wholesale_recommendation($p,$qty);
}
