<?php
declare(strict_types=1);
require_once __DIR__.'/icons.php';
require_once __DIR__.'/seo.php';
require_once __DIR__.'/seo-navigation.php';
function brand(): void {echo '<a class="brand" href="/" aria-label="نایلکس سادات؛ صفحه اصلی"><img src="/assets/logo.png" width="48" height="48" alt="" style="border-radius:12px"><span>نایلکس <b>سادات</b><small>SADAT NYLEX</small></span></a>';}
function enamad_seal(): void {?>
 <div class="container trust-seal"><span>استعلام اعتبار فروشگاه</span><a referrerpolicy="origin" target="_blank" rel="noopener" href="https://trustseal.enamad.ir/?id=7211806&amp;Code=dzZK2MjsBeqtPYf3SG6sYdHHguNwHsQT" aria-label="مشاهده اعتبار اینماد نایلکس سادات"><img referrerpolicy="origin" src="https://trustseal.enamad.ir/logo.aspx?id=7211806&amp;Code=dzZK2MjsBeqtPYf3SG6sYdHHguNwHsQT" alt="استعلام نماد اعتماد الکترونیکی" width="100" height="100" loading="lazy" code="dzZK2MjsBeqtPYf3SG6sYdHHguNwHsQT"></a></div>
<?php }
function category_mega_menu(): void {
 $tree=public_category_tree();?>
 <div class="nav-category-wrap"><button class="nav-category" type="button" aria-expanded="false" aria-controls="category-mega" data-category-toggle><?=icon('menu')?> دسته‌بندی محصولات</button><div class="category-mega" id="category-mega"><div class="category-mega-grid"><?php foreach($tree as$parent):?><section><details><summary class="category-parent"><?=h($parent['name'])?></summary><a href="<?=h(category_path($parent))?>">مشاهده دسته‌بندی</a><div class="category-sale-links"><a href="<?=h(category_path($parent))?>">محصولات و قیمت‌ها</a><a href="/wholesale?category=<?=$parent['id']?>">خرید عمده</a></div><?php if($parent['children']):?><ul><?php foreach($parent['children'] as$child):?><li><a href="<?=h(category_path($child))?>"><?=h(category_display_name($child))?></a><span class="category-sale-links"><a href="<?=h(category_path($child))?>">خرد</a><a href="/wholesale?category=<?=$child['id']?>">عمده</a></span></li><?php endforeach;?></ul><?php endif;?></details></section><?php endforeach;?></div><div class="category-all"><a href="/products">همه محصولات خرد</a><a href="/wholesale">همه محصولات عمده</a></div></div></div>
 <?php }
function page_header(string $title,string $description='',bool $index=true,string $canonical='',string $shareImage='',string $ogType='website'): void {
 $seoKey=match(parse_url($canonical,PHP_URL_PATH)){'/'=>'home','/wholesale'=>'wholesale','/about'=>'about',default=>null};if($index&&$seoKey&&empty(parse_url($canonical,PHP_URL_QUERY))){$title=content_text('seo.'.$seoKey.'.title','')?:$title;$description=content_text('seo.'.$seoKey.'.description','')?:$description;}
 global $nonce;$s=settings();$u=current_user();$fullTitle=str_starts_with($title,'نایلکس سادات _')?str_replace('نایلکس سادات _','نایلکس سادات |',$title):$title.' | نایلکس سادات';$description=$description?:'خرید خرده و عمده محصولات پلاستیکی، نایلون، نایلکس، کیسه فریزر و کیسه زباله از نایلکس سادات؛ پلاستیک سادات و سادات پخش.';if(!$index)header('X-Robots-Tag: noindex, follow');$canonical=$canonical?:url('/');$shareImage=$shareImage?:url('/assets/social-cover.png');
 ?><!doctype html><html lang="fa-IR" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($fullTitle)?></title><meta name="description" content="<?=h($description)?>"><meta name="robots" content="<?=$index?'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1':'noindex,follow'?>"><link rel="canonical" href="<?=h($canonical)?>"><link rel="alternate" hreflang="fa-IR" href="<?=h($canonical)?>"><meta property="og:title" content="<?=h($fullTitle)?>"><meta property="og:description" content="<?=h($description)?>"><meta property="og:url" content="<?=h($canonical)?>"><meta property="og:type" content="<?=h($ogType)?>"><meta property="og:locale" content="fa_IR"><meta property="og:site_name" content="نایلکس سادات"><meta property="og:image" content="<?=h($shareImage)?>"><meta property="og:image:alt" content="نایلکس سادات؛ فروش محصولات پلاستیکی"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon-96.png"><link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"><link rel="preload" href="/fonts/Vazirmatn.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="<?=h(asset_url('shop.css'))?>"><script src="<?=h(asset_url('shop.js'))?>" defer nonce="<?=h($nonce)?>"></script><?php $googleToken=content_text('seo.google_verification','');if($googleToken!==''):?><meta name="google-site-verification" content="<?=h($googleToken)?>"><?php endif;typography_styles();?></head><body><a href="#main-content" class="skip-link">رفتن به محتوای اصلی</a>
 <?php $org=['@context'=>'https://schema.org','@type'=>['Organization','Store'],'@id'=>url('/').'#organization','name'=>'نایلکس سادات','alternateName'=>['پلاستیک سادات','سادات پخش','بازرگانی سادات پخش','سادات پلاستیک'],'legalName'=>$s['company_name'],'description'=>'تولید و فروش مستقیم عمده و خرده نایلکس، نایلون و محصولات پلاستیکی در تهران برای بازار سراسر ایران','url'=>url('/'),'areaServed'=>['@type'=>'Country','name'=>'ایران'],'logo'=>['@type'=>'ImageObject','url'=>url('/assets/logo.png')],'image'=>url('/assets/social-cover.png'),'knowsAbout'=>['خرید عمده نایلکس','خرید عمده نایلون','فروش محصولات پلاستیکی','کیسه فریزر','کیسه زباله','نایلکس فروشگاهی']];if($s['company_phone'])$org['telephone']=$s['company_phone'];if($s['company_email'])$org['email']=$s['company_email'];$org['address']=['@type'=>'PostalAddress','addressLocality'=>'تهران','addressCountry'=>'IR'];if($s['company_address'])$org['address']['streetAddress']=$s['company_address'];if($s['company_postal_code'])$org['address']['postalCode']=$s['company_postal_code'];json_ld($org);json_ld(['@context'=>'https://schema.org','@type'=>'WebSite','@id'=>url('/').'#website','name'=>'نایلکس سادات','alternateName'=>['پلاستیک سادات','سادات پخش','بازرگانی سادات پخش'],'url'=>url('/'),'inLanguage'=>'fa-IR','publisher'=>['@id'=>url('/').'#organization'],'potentialAction'=>['@type'=>'SearchAction','target'=>url('/search').'?q={search_term_string}','query-input'=>'required name=search_term_string'],'hasPart'=>[['@type'=>'WebPage','name'=>'فروشگاه','url'=>url('/products')],['@type'=>'WebPage','name'=>'خرید عمده','url'=>url('/wholesale')],['@type'=>'WebPage','name'=>'محصولات پلاستیکی سادات','url'=>url('/plastic-products')],['@type'=>'WebPage','name'=>'تماس با ما','url'=>url('/contact')]]]);?>
 <div class="announcement"><span>از خانه تا کسب‌وکار، همراه همیشگی شما</span><span>خرید مستقیم، کیفیت مطمئن</span></div><header class="header"><div class="container header-main"><?php brand();?><form action="/search" class="search"><?=icon('search')?><input name="q" placeholder="دنبال چه محصولی می‌گردید؟" aria-label="جستجو" autocomplete="off" data-product-search><div class="search-suggestions" data-search-suggestions hidden role="listbox" aria-label="پیشنهاد محصولات"></div><button>جستجو</button></form><div class="header-actions"><a class="account-link" href="<?=$u?'/account':'/login'?>"><?=icon('user')?><span><?=$u?h($u['name']):'ورود / ثبت‌نام'?></span></a><i></i><?php cart_preview();?><button class="mobile-menu" type="button" data-menu aria-label="فهرست" aria-expanded="false"><?=icon('menu')?></button></div></div><nav class="container nav"><?php category_mega_menu();?><a href="/">صفحه اصلی</a><a href="/products">فروش خرد</a><a href="/wholesale">فروش عمده</a><a href="/guides">راهنمای خرید</a><a href="/track">پیگیری سفارش با کد رهگیری</a><a href="/about">درباره ما</a><a href="/contact">تماس با ما</a><?php if($u&&$u['role']==='ADMIN'):?><a href="/admin">مدیریت</a><?php endif;?></nav></header><main id="main-content">
 <?php if(isset($_SESSION['flash'])):[$kind,$message]=$_SESSION['flash'];unset($_SESSION['flash']);?><div class="container"><p class="<?=h($kind)?>" role="status"><?=h($message)?></p></div><?php endif;
}
function page_footer(): void {$s=settings();$wa=digits(content_text('company.whatsapp',''));if(str_starts_with($wa,'0'))$wa='98'.substr($wa,1);?></main><footer><div class="container footer-main"><div><?php brand();?><p>تولید و فروش مستقیم محصولات نایلکس و پلاستیکی برای خانه و کسب‌وکار؛ تهران و سراسر ایران.</p></div><div><h4>دسترسی سریع</h4><a href="/products">فروش خرد</a><a href="/wholesale">فروش عمده</a><a href="/track">پیگیری سفارش با کد رهگیری</a><a href="/guides">راهنمای خرید</a><a href="/about">درباره نایلکس سادات</a></div><div><h4>راهنمای مشتریان</h4><a href="/track">پیگیری سفارش</a><a href="/shipping">روش‌های ارسال</a><a href="/contact">تماس و پشتیبانی</a><a href="/faq">پرسش‌های متداول</a><a href="/terms">ضوابط و شرایط سایت</a><a href="/privacy">حریم خصوصی</a></div><div class="footer-note"><h4><?=h($s['company_name'])?></h4><?php if($s['company_phone']):?><a dir="ltr" href="tel:<?=h(preg_replace('/[ ()-]/','',$s['company_phone']))?>"><?=h($s['company_phone'])?></a><?php endif;?><p><?=h($s['company_address'])?></p><?php if($s['company_hours']):?><p><?=h($s['company_hours'])?></p><?php endif;?></div></div><?php enamad_seal();?><div class="container copyright"><span>تمامی حقوق برای نایلکس سادات محفوظ است.</span><span>با دقت انتخاب کنید، با خیال راحت خرید کنید.</span></div></footer><?php if(function_exists('support_floating_button'))support_floating_button();if($wa):?><a class="whatsapp-cta" href="https://wa.me/<?=h($wa)?>?text=<?=rawurlencode('سلام، برای خرید عمده مشاوره می‌خواهم.')?>" target="_blank" rel="noopener noreferrer">مشاوره خرید عمده در واتساپ</a><?php endif;?></body></html><?php }
function action_start(string $action,string $class='',string $target=''): void {echo '<form method="post" action="'.h($target?:'/'). '" class="'.h($class).'">';csrf_field();if($action==='cart_add')echo '<span class="product-cart-quantity" data-product-count aria-live="polite"></span>';echo '<input type="hidden" name="action" value="'.h($action).'">';}
function hidden(string $name,mixed $value): void {echo '<input type="hidden" name="'.h($name).'" value="'.h($value).'">';}
function product_card(array $p,string $context=''): void {$wholesaleView=$context==='wholesale';$explicitWholesale=is_wholesale_product($p);?><article class="product-card"><a class="product-image" href="/products/<?=h($p['slug'])?>"><span class="product-badge"><?=$wholesaleView||$explicitWholesale?'محصول عمده':'محصول خرده'?></span><img src="<?=h(display_image($p['image']))?>" alt="<?=h($p['name'])?>؛ <?=h($p['category_name']??'محصولات پلاستیکی')?>" width="350" height="280" loading="lazy" decoding="async" sizes="(max-width: 560px) 46vw, (max-width: 900px) 44vw, 350px"></a><div class="product-body"><span class="muted product-category"><?=h($p['category_name']??'محصولات')?></span><a href="/products/<?=h($p['slug'])?>"><h3><?=h($p['name'])?></h3></a><div class="product-meta"><span><?=$p['stock']?'موجود در انبار':'ناموجود'?></span><span>هر <?=h($wholesaleView||$explicitWholesale?'کیلوگرم':$p['unit'])?></span></div><div class="product-bottom"><div><small><?=$wholesaleView||$explicitWholesale?'قیمت عمده هر کیلو':'قیمت خرده'?></small><strong><?=money($wholesaleView?(int)$p['wholesale']:unit_price($p,1))?> <span>تومان</span></strong></div><?php if($wholesaleView||$explicitWholesale):?><a class="btn outline" href="/products/<?=h($p['slug'])?>">انتخاب وزن</a><?php else:quantity_control($p);endif;?></div><div class="wholesale-hint"><?php if($wholesaleView||$explicitWholesale):?>وزن پیشنهادی اولیه ۲۵ کیلوگرم است؛ وزن و مبلغ نهایی را در صفحه محصول انتخاب کنید.<?php else:product_sales_hint($p);endif;?></div></div></article><?php }
function password_form(): void {action_start('password','panel form-stack','/account');?><h2>تغییر رمز عبور</h2><?php field('رمز فعلی','current_password','','password');?><label>رمز جدید، حداقل ۸ کاراکتر<input name="new_password" type="password" required minlength="8" maxlength="72" autocomplete="new-password"></label><button class="btn">تغییر رمز و بستن نشست‌های قبلی</button></form><?php }

function quantity_control(array $p,bool $initialButton=false,bool $productDetail=false): void {
 $qty=(int)($_SESSION['cart'][$p['id']]??0);$max=min(1000,(int)$p['stock']);
 if($productDetail&&is_wholesale_product($p)){
  $selected=$qty?:min(25,max(1,$max));$tiers=wholesale_price_tiers($p);$active=wholesale_tier_for_quantity($p,$selected);$tierData=h(json_encode(['min2'=>$tiers['tier_2_min'],'min3'=>$tiers['tier_3_min'],'min4'=>$tiers['tier_4_min'],'prices'=>[$tiers['price_1'],$tiers['price_2'],$tiers['price_3'],$tiers['price_4']]],JSON_UNESCAPED_UNICODE));?>
  <form method="post" action="/" class="quantity-control wholesale-quantity-control" data-quantity-control data-wholesale-selector data-tier-config="<?=$tierData?>" data-max="<?=$max?>" data-qty="<?=$qty?>"><?php csrf_field();hidden('id',$p['id']);hidden('quantity',1);?><input type="hidden" name="requested_quantity" value="<?=$selected?>" data-wholesale-quantity>
  <div class="wholesale-selection-head"><strong>مقدار سفارش</strong><span>واحد محاسبه: کیلوگرم</span></div><div class="quantity-stepper" role="group" aria-label="انتخاب وزن <?=h($p['name'])?>"><button type="button" data-wholesale-minus aria-label="یک کیلو کاهش" <?=$selected<=1?'disabled':''?>>−</button><output data-product-count data-wholesale-count aria-live="polite"><?=money($selected)?> کیلو</output><button type="button" data-wholesale-plus aria-label="یک کیلو افزایش" <?=$selected>=$max?'disabled':''?>>+</button></div><div class="quantity-presets" role="group" aria-label="افزودن سریع وزن"><span>افزودن سریع:</span><?php foreach([1,2,5,10,25,50] as $amount):?><button type="button" data-wholesale-preset="<?=$amount?>">+<?=money($amount)?></button><?php endforeach;?></div>
  <div class="wholesale-calculation" aria-live="polite"><p><span>قیمت هر کیلو</span><strong data-wholesale-unit-price><?=money($active['price'])?> تومان</strong></p><p><span>محاسبه مبلغ</span><strong><b data-wholesale-formula><?=money($selected)?> × <?=money($active['price'])?></b> تومان</strong></p><p class="wholesale-total"><span>مبلغ کل</span><strong data-wholesale-total><?=money($selected*$active['price'])?> تومان</strong></p><small data-wholesale-range>سفارش شما با قیمت بازه <?=money($active['min'])?><?=$active['max']?' تا '.money($active['max']).' کیلو':' کیلو و بیشتر'?> محاسبه می‌شود.</small></div>
  <button type="submit" name="action" value="cart_set" class="btn wholesale-add" <?=$max?'':'disabled'?>><?=$qty?'به‌روزرسانی سبد خرید':'افزودن به سبد خرید'?></button><span data-cart-message role="status"></span></form><?php return;
 }
 ?><form method="post" action="/" class="quantity-control" data-quantity-control data-max="<?=$max?>" data-qty="<?=$qty?>">
 <?php csrf_field();hidden('id',$p['id']);hidden('quantity',1);?>
 <?php if($initialButton):?><button type="submit" name="action" value="cart_add" class="btn" data-first-add data-add-quantity="1" <?=$qty?'hidden':''?> <?=$max>0?'':'disabled'?>><?=$max>0?'افزودن به سبد خرید':'ناموجود'?></button><?php endif;?>
 <div class="quantity-stepper" <?=$initialButton&&$qty===0?'hidden':''?> role="group" aria-label="تعداد <?=h($p['name'])?>">
 <button type="submit" name="action" value="cart_decrease" data-minus aria-label="کاهش تعداد <?=h($p['name'])?>" <?=$qty?'':'disabled'?>>−</button>
 <output data-product-count aria-live="polite" aria-label="تعداد انتخاب‌شده"><?=money($qty)?></output>
 <button type="submit" name="action" value="cart_add" data-plus data-add-quantity="1" aria-label="افزایش تعداد <?=h($p['name'])?>" <?=$qty<$max?'':'disabled'?>>+</button>
 </div><small data-current-price>قیمت فعلی هر <?=h($p['unit'])?>: <?=money(unit_price($p,max(1,$qty)))?> تومان</small><span data-cart-message role="status"></span></form><?php wholesale_recommendation($p,$qty);
}
