<?php
declare(strict_types=1);
function wholesale_terms(): void { ?>
 <section class="panel seo-content"><h2>سه روش خرید با قیمت مناسب‌تر</h2>
 <h3>قیمت عمده خودکار</h3><?php editable_text('wholesale.public','قیمت عمده خودکار','حداقل خرید عمده برای هر محصول جداگانه تعیین می‌شود. برای محصول کیلویی می‌توان این آستانه را مثلاً ۱۰۰ کیلوگرم قرار داد؛ برای کالای بسته‌ای یا عددی، مقدار درج‌شده در واحد همان محصول ملاک است. با رسیدن تعداد همان کالا به آستانه، قیمت عمده خودکار اعمال می‌شود.');?>
 <h3>یک حساب برای همه مشتریان</h3><?php editable_text('wholesale.partner','حساب یکپارچه مشتری','نیازی به درخواست یا تأیید حساب همکاری نیست. هر مشتری پس از ثبت‌نام و ورود می‌تواند وارد پنل فروش عمده شود، قیمت‌ها را مقایسه کند و سفارش خرده یا عمده ثبت کند.');?>
 <h3>سفارش عمده ویژه</h3><?php editable_text('wholesale.special','سفارش عمده ویژه','سفارش‌های بالای ۱۰۰ کیلوگرم را برای بررسی شرایط ویژه با پشتیبانی هماهنگ کنید. تخفیف اضافه خودکار یا تضمین‌شده نیست و باید پیش از پرداخت تأیید شود. این استعلام مستقل از آستانه قیمت تعدادی هر محصول است.');?></section>
<?php }
function wholesale_landing(): void {
 page_header('ورود به پنل خرید عمده','ورود یا ثبت‌نام برای ثبت سفارش عمده محصولات پلاستیکی.',false,url('/wholesale-buying'));
 $u=current_user();
 ?><div class="container page-content"><h1>خرید عمده نایلون و نایلکس برای کسب‌وکار شما</h1><div class="seo-intro"><?php editable_text('wholesale.intro','معرفی فروش عمده','تأمین نایلکس، کیسه فریزر، کیسه زباله و محصولات بسته‌بندی برای سوپرمارکت‌ها، فروشگاه‌ها، عمده‌فروش‌ها، رستوران‌ها و مراکز پخش.');?></div><?php sales_navigation();wholesale_terms(); ?>
 <section class="panel seo-content"><h2>مزایای پنل فروش عمده</h2><p>مقایسه قیمت خرده و عمده، ثبت سریع تعداد، مشاهده میزان صرفه‌جویی و پیگیری خریدها با همان حساب معمولی سایت.</p><h2>ورود، ارسال و تسویه</h2><p>هیچ تأیید جداگانه‌ای لازم نیست. پس از ورود، مقدار هر کالا را انتخاب کنید؛ قیمت عمده در آستانه تعیین‌شده خودکار محاسبه می‌شود و تسویه آنلاین از درگاه انجام می‌شود.</p>
 <?php if(!$u):?><a class="btn" href="/register">ساخت حساب و خرید عمده</a> <a class="text-link" href="/login">ورود به حساب موجود</a>
 <?php else:?><a class="btn" href="/wholesale-panel">ورود به پنل فروش عمده</a><?php endif;?>
 <a class="text-link" href="/contact">هماهنگی ارسال و سفارش ویژه</a></section></div><?php page_footer();
}
function wholesale_panel(): void {
 $u=current_user();if(!$u)redirect('/login');
 $q=is_string($_GET['q']??null)?trim(mb_substr($_GET['q'],0,80)):'';$category=isset($_GET['category'])?number_input('category',0,PHP_INT_MAX,$_GET):0;
 $sql='SELECT p.*,c.name category_name FROM ns_products p JOIN ns_categories c ON c.id=p.category_id WHERE p.active=1 AND EXISTS (SELECT 1 FROM ns_product_sales s WHERE s.product_id=p.id AND s.sale_type=\'wholesale\')';$args=[];if($category){$sql.=' AND p.category_id=?';$args[]=$category;}if($q!==''){$sql.=' AND (p.name LIKE ? OR c.name LIKE ?)';$args[]='%'.$q.'%';$args[]='%'.$q.'%';}$products=all($sql.' ORDER BY p.stock>0 DESC,p.featured DESC,p.id DESC LIMIT 200',$args);
 $orders=all("SELECT code,status,total,created_at FROM ns_orders WHERE user_id=? ORDER BY id DESC LIMIT 8",[$u['id']]);$paid=one("SELECT COUNT(*) orders_count,COALESCE(SUM(total),0) total FROM ns_orders WHERE user_id=? AND status IN ('PAID','SHIPPED','DELIVERED')",[$u['id']]);$cart=cart_lines();$cartCount=0;$cartSaving=0;foreach($cart as$line)if(empty($line['missing'])){$cartCount+=(int)$line['quantity'];if((int)$line['quantity']>=(int)$line['minimum'])$cartSaving+=((int)$line['retail']-(int)$line['wholesale'])*(int)$line['quantity'];}
 page_header('پنل فروش عمده','',false,url('/wholesale-panel'));
 ?><div class="container page-content wholesale-dashboard"><header class="wholesale-head"><div><span class="status">پنل خرید عمده</span><h1>سلام <?=h($u['name'])?>، پنل فروش عمده شما آماده است</h1><p>برای هر محصول با رسیدن تعداد به آستانه درج‌شده، قیمت عمده خودکار اعمال می‌شود. مبلغ نهایی و موجودی هنگام تسویه دوباره در سرور کنترل خواهد شد.</p></div><div class="buy-row"><a class="btn" href="/cart">سبد عمده · <?=money($cartCount)?> کالا</a><a class="btn outline" href="/shipping">روش‌های ارسال</a></div></header>
 <section class="wholesale-stats"><article class="panel"><small>خریدهای پرداخت‌شده</small><strong><?=money($paid['orders_count']??0)?></strong><span>سفارش</span></article><article class="panel"><small>ارزش خریدهای ثبت‌شده</small><strong><?=money($paid['total']??0)?></strong><span>تومان</span></article><article class="panel"><small>صرفه‌جویی سبد فعلی</small><strong><?=money($cartSaving)?></strong><span>تومان</span></article><article class="panel"><small>روش محاسبه</small><strong>خودکار</strong><span>بر اساس آستانه هر محصول</span></article></section>
 <nav class="wholesale-shortcuts panel" aria-label="دسترسی سریع"><a href="#quick-order">سفارش سریع</a><a href="#wholesale-catalog">لیست قیمت عمده</a><a href="#recent-orders">سفارش‌های اخیر</a><a href="/track">پیگیری سفارش</a><a href="/contact">پشتیبانی فروش عمده</a></nav>
 <section id="quick-order" class="panel wholesale-quick"><div class="section-heading"><div><span class="eyebrow">ثبت سریع تعداد</span><h2>سفارش سریع عمده</h2></div><a href="/cart">مشاهده سبد و جمع نهایی ←</a></div><div class="table-scroll"><table><thead><tr><th>محصول</th><th>موجودی</th><th>قیمت مصرف‌کننده</th><th>قیمت همکاری شما</th><th>صرفه‌جویی واحد</th><th>تعداد در سبد</th></tr></thead><tbody><?php foreach(array_slice($products,0,12)as$p):?><tr><td><a href="/products/<?=h($p['slug'])?>"><strong><?=h($p['name'])?></strong><small><?=h($p['category_name'])?> · هر <?=h($p['unit'])?></small></a></td><td><?=$p['stock']?money($p['stock']).' '.$p['unit']:'ناموجود'?></td><td><del><?=money($p['retail'])?></del></td><td><strong><?=money($p['wholesale'])?> تومان</strong></td><td><?=money((int)$p['retail']-(int)$p['wholesale'])?> تومان</td><td><?php quantity_control($p,true);?></td></tr><?php endforeach;?></tbody></table></div></section>
 <section id="wholesale-catalog"><div class="section-heading"><div><span class="eyebrow">قابل سفارش برای همه مشتریان</span><h2>کاتالوگ قیمت عمده</h2></div><span><?=money(count($products))?> محصول</span></div><form class="panel wholesale-filter" action="/wholesale-panel"><label>جست‌وجوی نام یا دسته<input name="q" value="<?=h($q)?>" placeholder="مثلاً کیسه فریزر"></label><label>دسته‌بندی<select name="category"><option value="0">همه دسته‌ها</option><?php foreach(seo_categories()as$c):?><option value="<?=$c['id']?>" <?=$category===(int)$c['id']?'selected':''?>><?=h($c['name'])?></option><?php endforeach;?></select></label><button class="btn">نمایش</button><?php if($q!==''||$category):?><a class="btn outline" href="/wholesale-panel">حذف فیلتر</a><?php endif;?></form><div class="product-grid wholesale-products"><?php foreach($products as$p):?><article class="panel wholesale-product"><a href="/products/<?=h($p['slug'])?>"><img src="<?=h($p['image'])?>" alt="<?=h($p['name'])?>" width="240" height="180" loading="lazy"><span class="muted"><?=h($p['category_name'])?></span><h2><?=h($p['name'])?></h2></a><div class="wholesale-price"><small>قیمت مصرف‌کننده</small><del><?=money($p['retail'])?> تومان</del><small>قیمت عمده</small><strong><?=money($p['wholesale'])?> تومان</strong></div><p>قیمت عمده از <?=money($p['minimum'])?> <?=h($p['unit'])?> خودکار اعمال می‌شود؛ صرفه‌جویی هر واحد <?=money((int)$p['retail']-(int)$p['wholesale'])?> تومان است.</p><p class="stock-state <?=$p['stock']?'in-stock':'out-stock'?>"><?=$p['stock']?'موجود · '.money($p['stock']).' '.$p['unit']:'ناموجود'?></p><?php quantity_control($p,true);?></article><?php endforeach;if(!$products):?><div class="empty-state"><h3>محصولی با این فیلتر پیدا نشد</h3><a class="btn" href="/wholesale-panel">نمایش همه محصولات عمده</a></div><?php endif;?></div></section>
 <section id="recent-orders" class="panel wholesale-orders"><div class="section-heading"><h2>سفارش‌های اخیر</h2><a href="/account">همه سفارش‌ها ←</a></div><?php if($orders):?><div class="table-scroll"><table><thead><tr><th>کد سفارش</th><th>تاریخ</th><th>وضعیت</th><th>مبلغ</th><th></th></tr></thead><tbody><?php foreach($orders as$order):?><tr><td dir="ltr"><?=h($order['code'])?></td><td><?=h(substr($order['created_at'],0,10))?></td><td><span class="status"><?=h(order_status($order['status']))?></span></td><td><?=money($order['total'])?> تومان</td><td><a href="/track?code=<?=h($order['code'])?>">پیگیری</a></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="empty-state compact"><h3>هنوز سفارش عمده‌ای ندارید</h3><p>از سفارش سریع، تعداد کالاها را به سبد اضافه کنید.</p><a class="btn" href="#quick-order">شروع سفارش</a></div><?php endif;?></section>
 <section class="panel wholesale-help"><div><h2>برای سفارش ویژه یا حجم بالا نیاز به راهنمایی دارید؟</h2><p>مشخصات محصول، مقدار و مقصد را برای پشتیبانی ارسال کنید. شرایطی که هنوز در سایت درج نشده باید پیش از پرداخت تأیید شود.</p></div><a class="btn" href="/contact">مشاوره خرید عمده</a></section></div><?php page_footer();
}
function shop_faq(): array {return [
 ['key'=>'minimum','question'=>'حداقل خرید عمده چقدر است؟','answer'=>content_text('faq.minimum','مقدار هر کالا در صفحه محصول مشخص است. پیش‌فرض محصولات جدید ۵۰ کیلوگرم است؛ برای محصولات بسته‌ای، تعداد بسته درج‌شده ملاک است. مدیر می‌تواند حداقل هر کالا را جداگانه تعیین کند.')],
 ['key'=>'pricing','question'=>'قیمت عمده چگونه محاسبه می‌شود؟','answer'=>content_text('faq.pricing','با رسیدن مقدار همان کالا به حداقل درج‌شده، قیمت عمده برای همه واحدهای همان کالا خودکار اعمال می‌شود. نیازی به حساب همکاری یا تأیید مدیر نیست.')],
 ['key'=>'delivery_time','question'=>'ارسال چند روز طول می‌کشد؟','answer'=>content_text('faq.delivery_time','')],
 ['key'=>'delivery_method','question'=>'ارسال با چه روشی انجام می‌شود؟','answer'=>content_text('faq.delivery_method','')],
 ['key'=>'in_person','question'=>'آیا خرید حضوری دارید؟','answer'=>content_text('faq.in_person','')],
 ['key'=>'invoice','question'=>'آیا فاکتور صادر می‌شود؟','answer'=>content_text('faq.invoice','')],
 ['key'=>'returns','question'=>'محصول معیوب قابل مرجوعی است؟','answer'=>content_text('faq.returns','')],
 ['key'=>'custom','question'=>'امکان تولید سفارشی هست؟','answer'=>content_text('faq.custom','')],
 ['key'=>'payment','question'=>'اگر پرداخت ناموفق بود چه کنم؟','answer'=>content_text('faq.payment','کد سفارش را نگه دارید و با شماره موبایل گیرنده در صفحه پیگیری، وضعیت را بررسی کنید. برای پیگیری کسر وجه یا نتیجه نامشخص با پشتیبانی تماس بگیرید.')],
 ];}
function faq_page(): void {
 $all=shop_faq();$faq=array_values(array_filter($all,fn($q)=>$q['answer']!==''));page_header('پرسش‌های متداول خرید و فروش عمده','پاسخ پرسش‌های خرید عمده نایلکس، حداقل سفارش، قیمت همکاری و پرداخت.',true,url('/faq'));
 json_ld(['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>array_map(fn($q)=>['@type'=>'Question','name'=>$q['question'],'acceptedAnswer'=>['@type'=>'Answer','text'=>$q['answer']]],$faq)]);
 ?><div class="container page-content"><article class="panel prose"><h1>پرسش‌های متداول</h1><section class="buying-faq"><h2>پیش از خرید بدانید</h2><?php foreach($faq as$q):?><details><summary><?=h($q['question'])?></summary><?php editable_text('faq.'.$q['key'],'پاسخ: '.$q['question'],$q['answer']);?></details><?php endforeach;?></section><?php if((current_user()['role']??'')==='ADMIN'):?><section class="seo-content"><h2>پاسخ‌های تکمیل‌نشده</h2><p>این موارد برای مشتری و Schema منتشر نشده‌اند. پس از ذخیره پاسخ، منتشر می‌شوند.</p><?php foreach($all as$q):if($q['answer']===''):?><h3><?=h($q['question'])?></h3><?php editable_text('faq.'.$q['key'],'پاسخ: '.$q['question'],'');endif;endforeach;?></section><?php endif;?><a class="btn" href="/wholesale">خرید عمده</a> <a class="text-link" href="/contact">تماس و پشتیبانی</a></article></div><?php page_footer();
}
