import { db } from '@/lib/db';
import { currentUser } from '@/lib/auth';
import { AuthForm,CartPage,Logout,TrackForm } from '@/components/shop';
import { notFound,redirect } from 'next/navigation';
import Link from 'next/link';
import { companySettings,siteURL,siteName } from '@/lib/site';
import { PasswordForm } from '@/components/password-form';
import { CompanyInfo } from '@/components/company-info';
const titles:Record<string,string>={cart:'سبد خرید',checkout:'تکمیل سفارش',login:'ورود به حساب',wholesale:'درخواست حساب عمده',account:'حساب کاربری',track:'پیگیری سفارش',about:'درباره ما',contact:'تماس با ما',faq:'پرسش‌های متداول'};
export async function generateMetadata({params}:{params:Promise<{page:string}>}){const {page}=await params;const index=['about','contact','faq'].includes(page);const description=page==='about'?'درباره نایلکس سادات و تأمین محصولات نایلون، نایلکس و بسته‌بندی.':page==='contact'?'اطلاعات تماس، نشانی و ساعات پاسخ‌گویی نایلکس سادات.':'پاسخ پرسش‌های خرید عمده، ارسال و پیگیری سفارش نایلکس سادات.';return {title:titles[page]||'صفحه پیدا نشد',description,alternates:{canonical:siteURL('/'+page)},robots:{index,follow:index},openGraph:{images:['/social-cover.png'],title:titles[page],description,url:siteURL('/'+page),siteName,locale:'fa_IR',type:'website' as const}}}
export default async function Page({params,searchParams}:{params:Promise<{page:string}>;searchParams:Promise<{code?:string;payment?:string}>}){const {page}=await params;if(!titles[page])notFound();const user=await currentUser();let content;
 if(page==='cart'||page==='checkout'){const [products,settings]=await Promise.all([db.product.findMany({where:{active:true},include:{category:true}}),db.settings.findUniqueOrThrow({where:{id:'shop'}})]);content=<CartPage products={products} settings={settings} approved={user?.wholesaleStatus==='APPROVED'} checkout={page==='checkout'}/>}
 else if(page==='login'||page==='wholesale'){if(user)redirect('/account');content=<AuthForm register={page==='wholesale'}/>}
 else if(page==='track'){const q=await searchParams;content=<TrackForm code={q.code} payment={q.payment}/>}
 else if(page==='account'){if(!user)redirect('/login');const orders=await db.order.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'},take:30});content=<div className="panel account-panel"><h1>سلام، {user.name}</h1><p>وضعیت حساب عمده: {{NONE:'عادی',PENDING:'در انتظار بررسی',APPROVED:'تأیید شده',REJECTED:'تأیید نشده'}[user.wholesaleStatus]}</p>{user.role==='ADMIN'&&<Link className="btn" href="/admin">ورود به پنل مدیریت</Link>}<h2>سفارش‌های شما</h2>{orders.length?orders.map(o=><p key={o.id}><Link href={`/track?code=${o.code}`}>{o.code} ← مشاهده وضعیت</Link></p>):<p className="muted">هنوز سفارشی ثبت نکرده‌اید.</p>}<Logout/><PasswordForm/></div>}
 else {const company=await companySettings();content=<article className="panel prose"><span className="eyebrow">نایلکس سادات</span><h1>{titles[page]}</h1>{page==='about'&&company.companyAbout?<p style={{whiteSpace:'pre-line'}}>{company.companyAbout}</p>:page==='about'?<><h2>همراه خانه و کسب‌وکار شما</h2><p>نایلکس سادات فروشگاه محصولات پلاستیکی و بسته‌بندی است. هدف ما ساده‌تر کردن تهیه نیازهای روزمره، با امکان خرید خرده و عمده و قیمت‌گذاری شفاف است.</p><p>کیسه فریزر، کیسه زباله، نایلون و نایلکس را بر اساس نیازتان انتخاب کنید. در هر محصول، حداقل تعداد خرید عمده مشخص شده است.</p><Link className="btn" href="/products">دیدن محصولات</Link></>:page==='contact'?<><h2>برای انتخاب بهتر، با ما در ارتباط باشید</h2><CompanyInfo company={company}/><h3>پیگیری خرید</h3><p>برای بررسی وضعیت پرداخت و ارسال، از کد سفارش و شماره موبایل خود استفاده کنید.</p><Link className="btn" href="/track">پیگیری سفارش</Link></>:<>{[['چطور با قیمت عمده خرید کنم؟','با رسیدن تعداد هر محصول به حداقل خرید عمده، قیمت همکاری خودکار اعمال می‌شود. مشتریان عمده تأییدشده برای هر تعداد از قیمت عمده استفاده می‌کنند.'],['هزینه ارسال چگونه محاسبه می‌شود؟','هزینه ارسال ثابت است و در سبد خرید نمایش داده می‌شود. حد ارسال رایگان را نیز در خلاصه سفارش مشاهده می‌کنید.'],['چگونه سفارش را پیگیری کنم؟','کد سفارش و موبایل گیرنده را در صفحه پیگیری وارد کنید. پس از پرداخت، کد سفارش به شما نمایش داده می‌شود.'],['اگر پرداخت ناموفق بود چه کنم؟','کد سفارش را نگه دارید و با پشتیبانی تماس بگیرید. سفارش تا تأیید سرور درگاه، پرداخت‌شده محسوب نمی‌شود.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</>}</article>;}
 return <div className="container page-content">{content}</div>}
