import secrets
from playwright.sync_api import sync_playwright,expect
base='http://localhost:8085'
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True)
 page=browser.new_page()
 page.goto(base+'/')
 page.get_by_role('link',name='ثبت‌نام',exact=True).click()
 expect(page).to_have_url(base+'/register')
 phone='09'+''.join(str(secrets.randbelow(10)) for _ in range(9));password=secrets.token_urlsafe(20)
 page.locator('[name=name]').fill('آزمون حساب مشتری')
 page.locator('[name=username]').fill(phone)
 page.locator('[name=password]').fill(password)
 page.get_by_role('button',name='ساخت حساب کاربری',exact=True).click()
 expect(page).to_have_url(base+'/account')
 page.get_by_role('button',name='خروج از حساب',exact=True).click()
 expect(page).to_have_url(base+'/')
 # A new browser session must authenticate using only the persisted account.
 page.close()
 page=browser.new_page()
 page.goto(base+'/login')
 page.locator('[name=username]').fill(phone.translate(str.maketrans('0123456789','۰۱۲۳۴۵۶۷۸۹')))
 page.locator('[name=password]').fill(password)
 page.get_by_role('button',name='ورود به حساب',exact=True).click()
 expect(page).to_have_url(base+'/account')
 print('PASS logout and login in fresh browser session with Persian mobile digits')
 page.goto(base+'/register')
 page.get_by_role('button',name='خروج و استفاده از حساب دیگر').click()
 expect(page).to_have_url(base+'/register')
 page.locator('[name=name]').fill('آزمون حساب مشتری')
 page.locator('[name=username]').fill(phone)
 page.locator('[name=password]').fill(password)
 page.get_by_role('button',name='ساخت حساب کاربری',exact=True).click()
 expect(page).to_have_url(base+'/login')
 expect(page.locator('[name=username]')).to_have_value(phone)
 page.locator('[name=password]').fill('wrong-password-123')
 page.get_by_role('button',name='ورود به حساب',exact=True).click()
 expect(page).to_have_url(base+'/login')
 expect(page.locator('[name=action]')).to_have_value('login')
 page.locator('[name=username]').fill(phone);page.locator('[name=password]').fill(password)
 page.get_by_role('button',name='ورود به حساب',exact=True).click()
 expect(page).to_have_url(base+'/account')
 print('PASS header registration, account switching and customer login')
 page.goto(base+'/products/product-1')
 page.locator('[data-plus]').click()
 expect(page.locator('[data-product-count]')).to_have_text('۱')
 assert page.locator('[data-product-total]').count()==0
 page.locator('[data-plus]').click()
 expect(page.locator('[data-product-count]')).to_have_text('۲')
 page.reload();expect(page.locator('[data-product-count]')).to_have_text('۲')
 print('PASS duplicate registration redirects to login; wrong password rejected; quantity preserved without multiplication')
 browser.close()
