import json, secrets, subprocess
from playwright.sync_api import sync_playwright, expect

base='http://localhost:8085'
fixture=[r'C:\xampp\php\php.exe','scripts/article-test-fixture.php']
slug='article-test-'+secrets.token_hex(8)
creds=json.loads(subprocess.check_output(fixture+['create',slug]))
try:
 with sync_playwright() as p:
  browser=p.chromium.launch(headless=True)
  for width in [390,1366]:
   page=browser.new_page(viewport={'width':width,'height':900})
   page.goto(base)
   box=page.locator('[data-product-search]');box.fill('کیسه')
   results=page.locator('[data-search-suggestions]');expect(results).to_be_visible()
   expect(results.locator('img').first).to_be_visible()
   expect(results.locator('b').first).to_contain_text('تومان')
   assert results.bounding_box()['y']>=box.bounding_box()['y']+box.bounding_box()['height']
   box.press('ArrowDown');page.keyboard.press('Enter');page.wait_for_url('**/products/**')
   page.close()
  page=browser.new_page();page.goto(base+'/login')
  page.locator('[name=username]').fill(creds['username']);page.locator('[name=password]').fill(creds['password'])
  page.locator('.auth-form button[type=submit], .auth-form button.btn').first.click()
  page.wait_for_url('**/admin');page.goto(base+'/admin?tab=articles&edit=0')
  page.locator('[name=title]').fill('آزمون مقاله همراه تصویر')
  page.locator('[name=slug]').fill(slug)
  page.locator('[name=excerpt]').fill('خلاصه اختصاصی برای بررسی مقاله همراه با تصویر و متن در محیط آزمایشی فروشگاه.')
  page.locator('[name=body]').fill('متن آزمایش مقاله و تصویر. '*15+'<script>window.bad=true</script>')
  # An actual PNG generated by the browser, submitted through multipart upload.
  png=page.locator('h1').screenshot()
  page.locator('[name=photo]').set_input_files({'name':'article.png','mimeType':'image/png','buffer':png})
  page.get_by_role('button',name='ذخیره مقاله',exact=True).click();page.wait_for_url('**/admin?tab=articles')
  page.goto(base+'/articles/'+slug)
  expect(page.locator('h1')).to_have_text('آزمون مقاله همراه تصویر')
  picture=page.locator('.article-body>img');expect(picture).to_be_visible()
  assert picture.get_attribute('src').startswith('/media?name=')
  assert page.evaluate('window.bad===undefined')
  assert page.locator('.article-text').inner_text().endswith('<script>window.bad=true</script>')
  print('PASS responsive search with image/price, keyboard navigation, administrator multipart image upload, article text escaping')
  browser.close()
finally:
 subprocess.run(fixture+['cleanup',slug],check=True)
