import { cache } from 'react';
import { db } from '@/lib/db';
import { currentUser } from '@/lib/auth';
import { ProductDetail,ProductCard } from '@/components/shop';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { siteName,siteURL } from '@/lib/site';
import { StructuredData } from '@/components/structured-data';
const getProduct=cache(async(slug:string)=>{const p=await db.product.findUnique({where:{slug},include:{category:true}});if(!p?.active)notFound();return p;});
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const p=await getProduct((await params).slug);return {title:`خرید ${p.name}`,description:p.description.slice(0,155),alternates:{canonical:siteURL('/products/'+p.slug)},openGraph:{title:p.name,description:p.description.slice(0,155),url:siteURL('/products/'+p.slug),siteName,locale:'fa_IR',images:[{url:p.image,alt:p.name}]},twitter:{card:'summary' as const,title:p.name,description:p.description.slice(0,155),images:[p.image]}}}
export default async function Detail({params}:{params:Promise<{slug:string}>}){const p=await getProduct((await params).slug);const user=await currentUser();const related=await db.product.findMany({where:{active:true,categoryId:p.categoryId,id:{not:p.id}},include:{category:true},take:4});return <div className="container page-content"><StructuredData data={{'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description,image:[siteURL(p.image)],sku:p.id,category:p.category.name,offers:{'@type':'Offer',url:siteURL('/products/'+p.slug),price:p.retail*10,priceCurrency:'IRR',availability:p.stock>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',itemCondition:'https://schema.org/NewCondition',seller:{'@type':'Organization',name:siteName}}}}/><StructuredData data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'خانه',item:siteURL()},{name:'محصولات',item:siteURL('/products')},{name:p.name,item:siteURL('/products/'+p.slug)}].map((i,n)=>({'@type':'ListItem',position:n+1,...i}))}}/><nav aria-label="مسیر صفحه" className="breadcrumbs"><Link href="/">خانه</Link> / <Link href="/products">محصولات</Link> / {p.name}</nav><ProductDetail product={p} approved={user?.wholesaleStatus==='APPROVED'}/>{related.length>0&&<section><div className="section-heading"><h2>محصولات مرتبط</h2></div><div className="product-grid">{related.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</div>}
